### ISSUE TITLE
ajouter un code google analytics dans les notes

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#1]
Bonjour,

dans le cadre d'une utilisation des notes comme FAQ, documentation,... serait-il possible d'ajouter un code de suivi google analytics ?

Merci.

Emmanuel

**Comment by cavo789** [comment]
Bonjour Emmanuel. 

Tous les templates sont surchargeables et donc tu peux déjà parfaitement le faire. 

Mon wiki explique comment créer une surcharge (cherche le mot Template) 

Bonne journée

**Comment by elecoest** [comment]
merci :)

**Comment by cavo789** [comment]
Je reviens sur notre discussion : va voir ce lien https://github.com/cavo789/marknotes/wiki/4.3-Use-yours-owns-templates qui explique, brièvement à ce jour, que tu peux créer tes propres templates.

Tu vas dans le dossier /templates et tu dupliques p.ex. le fichier screen.php et tu le nommes perso.php. Puis, dans settings.json, tu répères le noeud `templates` et pour l'attribut `screen` tu changes la valeur par perso.php.

Dès cet instant, l'affichage d'une note se fera via ton template perso et puisque settings.json n'est pas écrasé en mettant à jour le logiciel marknotes, ta modification est pérenne.

Bonne soirée.

**Comment by elecoest** [comment]
yes j'ai vu :)

la je cherche un template pour mes présentation sexy ^^


Le 12 avril 2017 à 19:37, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by cavo789** [comment]
Je suis preneur de toute idée d'amélioration de mon template de base ;-)

Pour l'instant il est très fonctionnel mais peu esthétique. Ce serait un atout de pouvoir en accroître le côté visuel ;-)
