### ISSUE TITLE
erreur dans l'entete de la page template HTML

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#10]
depuis la dernière version j'ai une entete qui est surprenante...

exemple : 
http://marknotes.allevents3.com/docs/AllEvents/plugins
/AcyMailing%20Tag%20and%20Filters%20:%20AllEvents.html?format=html

**Comment by cavo789** [comment]
Ce qui te surprend, c'est quoi ? On est bien d'accord que c'est ce `format=html` qui est superflu puisque l'extension du fichier est déjà .html.  Comment as-tu fait pour obtenir ce lien s'il te plaît ? (où as-tu cliqué?)

**Comment by elecoest** [comment]
le lien je l'ai trouvé en cliquant sur le mode screen en haut à droite :
ouvrir en externe.

ce qui me surprend c'est " /> " /> " /> " /> en haut à gauche de la page.

http://marknotes.allevents3.com/docs/AllEvents/com_allevents.html
  ca se voit avec chrome

Le 19 avril 2017 à 10:08, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by elecoest** [comment]
origine : c'est quand tu met une image dans le titre. retiré image, retiré bug.
