### ISSUE TITLE
custom.css ne semble pas fonctionner chez moi

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#11]
J'ai créé un custom.css à la racine de marknotes mais il semblerait qu'il ne soit pas pris en charge. j'ai loupé un truc ?

**Comment by cavo789** [comment]
Vérifie que le fichier soit bien chargé car sur ma machine, testé à l'instant, c'est pourtant OK.
Vérifie que ton sélecteur soit bien correct.

![2017-04-19_10h06_16](https://cloud.githubusercontent.com/assets/355999/25169606/e4d2224a-24e7-11e7-9e59-9f7208a8828b.png)

**Comment by elecoest** [comment]
comme tu peux le voir :
http://marknotes.allevents3.com/docs/AllEvents/com_allevents.html le
custom.css n'est pas chargé :/

2017-04-19 10:07 GMT+02:00 Christophe Avonture <notifications@github.com>:

**Comment by cavo789** [comment]
Ok, tu n'as pas été assez précis : tu ne parles pas de l'interface mais de la vue .html (dans le template de même nom), je regarde ça.

**Comment by elecoest** [comment]
oups désolé, c'est bien avec le template HTML que je rencontre le souci. en
mode screen le seul truc qui est dérangeant c'est la partie css

#CONTENT img {

   1. max-width: 800px;
   2. padding: 25px 5px;
   3. display: block;

}

qui implique que toutes les images sont un peu brutes.

perso je vais retirer :
#CONTENT img {

   1. max-width: 800px;
   2. /*padding: 25px 5px;*/
   3. /* display: block;*/

}

2017-04-19 10:28 GMT+02:00 Christophe Avonture <notifications@github.com>:

**Comment by cavo789** [comment]
Adapté.

Remarque : le display:block, c'est pour que chaque image soit seule sur sa ligne parce que sinon, tu pourrais avoir une petite image et, donc, un texte qui va déborder sur la droite de l'image ce qui n'est pas très beau.

Vu que c'est du markdown, on ne devrait pas jouer avec des css dans la note d'où mon display:block.

![2017-04-19_10h45_00](https://cloud.githubusercontent.com/assets/355999/25171196/47249af4-24ed-11e7-9723-f25d701caf83.png)

**Comment by elecoest** [comment]
ok je vais dans ce cas là trouver un "truc" pour contourner çà car dans mon
cas je souhaite 2 images sur la même ligne :)

Merci m'sieur !

Le 19 avril 2017 à 10:46, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by cavo789** [comment]
Fusionner les deux images en une seule :-)

Si tu trouves quelque chose, dis-le moi.

**Comment by elecoest** [comment]
Je peux pas c'est des images générées à la volée :). Mais oui je te dis
quoi

Le 19 avr. 2017 10:48, "Christophe Avonture" <notifications@github.com> a
écrit :
