### ISSUE TITLE
intégrer un bloc partage Facebook 

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#12]
dans le json de paramétrage : activer ou non le bloc FB

contenu du bloc FB juste après le <body>
		
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.9&appId=477951479261233";
		fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>	

intégration du bouton FB : 
<span class="fb-share-button" style="float: right;" data-href="%URL_PAGE%" data-layout="button_count"></span>

le tout mieux expliqué que moi : https://developers.facebook.com/docs/plugins/share-button

**Comment by cavo789** [comment]
Programmé sous la forme de plugin.

Toutefois j'ai un souci : j'aurai aimé une url type facebook/sharer.php qui permet de partager un lien or sharer.php n'existe plus.   Dans ton exemple ainsi que sur le sdk de FB, il est impératif d'avoir l'ID d'une application, c'est lourd...

**Comment by cavo789** [comment]
Va voir https://www.marknotes.fr/docs/CMS/Joomla/JUGToulouse/JUGToulouse.html.

Reste à coder correctement le partage Facebook.

Et oui, même en dehors de Joomla, les plugins, c'est topissime ! :-)

**Comment by elecoest** [comment]
hello, c'est à coder par un développer ? donc normalement il sait comment récupérer son application ID Facebook...

**Comment by cavo789** [comment]
Mmmmmm pas trop convaincu. Tu pars de ton besoin qui est celui d'un développeur ayant une page FB.

Si je suis un "simple" utilisateur, je mets ma petite documentation, mes notes, etc dans marknotes mais je n'ai pas de page application FB et là, donc, je n'ai pas de Appid.

Et puis, dans mon cas p.ex. : j'utilise marknotes pour déposer une documentation sur p.ex. Joomla, si je veux utiliser mon bouton "Partager Facebook", c'est en tant que Christophe que je souhaite partager, pas en tant que l'application TrucBidule...

Non ? 

J'aimerais de mon côté, donc, un partage qui ne soit pas obligatoirement lié à un Appid.

Note : regarde le code source du plugin content/html/share.php, il est vraiment simple, n'hésite pas à  proposer une modification.
