### ISSUE TITLE
intégrer un bloc google analytics

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#13]
dans les parametres json ajouter un identifiant GA.

si il est défini , reprise de ce code juste après le bloc 

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-xxxxx-x', 'auto');
ga('send', 'pageview');
</script>

**Comment by cavo789** [comment]
Deux minutes !

Programmé en deux minutes sous la forme d'un plugin.  Oh yeah
