### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by ced1870** [cavo789/marknotes#14]
le rendu n'est pas responsive en hauteur
il faut virer le JS qui donne la hauteur en min-height et max-height sur CONTENT et lui ajouter cette règle CSS
`height: calc(100vh - 12px);`

**Comment by cavo789** [comment]
Salut Cédric

J'ai souhaité un peu retravailler le côté responsive mais j'ai été assez vite bloqué.

Si je retire le code js que tu pointais càd

```js
$('#TDM').css('min-height', $(window).height() - 30);
$('#CONTENT').css('min-height', $(window).height() - 10);
```

qui se trouvent dans le fichier /assets/js/marknotes.js alors j'ai un "side-effect" : quand je ferme le treeview en fermant les dossiers, la hauteur de la zone change aussi et devient plus petite.

Un exemple : en faisant un clic droit sur le treeview, choisir "Fermer l'arbre" et tu comprendras : la zone n'inclue même plus le treeview...

**Comment by cavo789** [comment]
I'll close this issue since the version 2.0 of marknotes fully address this problem.

By the use of the [AdminLTE template](https://github.com/almasaeed2010/AdminLTE) + custom code, marknotes is now fully responsive.
