### ISSUE TITLE
plugin sitename | title

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#17]
Template : SCREEN

pouvoir mettre nos propre nom de site, titre, description...
pouvoir modifier le logo et le lien du logo
pouvoir modifier le design de la partie treeview
ajouter un Powered by Marknotes au dessus de la version de l'outil

Merci pour le google analytics c'est cool !

**Comment by cavo789** [comment]
Temps de programmation : moins de cinq minutes :-)

Va voir le nouveau fichier screen.php, en ligne 14 : https://github.com/cavo789/marknotes/blob/master/src/templates/screen.php#L14

Et va voir le nouveau plugin Meta : https://github.com/cavo789/marknotes/blob/master/src/plugins/content/html/meta.php

L'idée est de copier le fichier https://github.com/cavo789/marknotes/blob/master/src/plugins/content/html/meta/meta.txt.dist et de créer ta version nommée meta.txt (à mettre dans le même dossier).

Développé en cinq minutes, tu me tiens au jus si tout fonctionne comme tu le souhaitais ? 

A++

Tu personnalises meta.txt et c'est tout.
