### ISSUE TITLE
A component for joomla installation

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#18]
hello it will be to create a quick package to install and edit config in joomla

**Comment by cavo789** [comment]
Salut Yannick

Sorry mais cela sort complètement de mon objectif. Perso, je ne coderais pas cela mais serait heureux si quelqu'un le fait.

L'objectif que je poursuis avec marknotes, c'est de donner une alternative valable (et sur certains points meilleures) à des outils comme Evernote et OneNote.  Meilleure pour p.ex. l'ouverture et la gestion des slideshows.

Mon objectif n'est pas de m'intégrer dans un CMS (peu importe lequel).

Je me permets de clôturer cette proposition car, de mon côté, ce sera un NODO (à l'opposé d'un TODO ;-) ).

J'espère que tu comprendras les limites que je me fixe.

Bonne journée.

**Comment by micker** [comment]
pas de soucis je comprend trés bien !
