### ISSUE TITLE
refresh du cache

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#2]
Une idée pour le cache : mettre un icone de type refresh plutot que le gomme.

Je dis çà car j'ai cherché un peu ^^

**Comment by cavo789** [comment]
Merci pour l'info, je vais voir si je peux trouver une autre icône.

Je ne puis toutefois pas utiliser l'icône "refresh" à la place de la gomme car j'utilise déjà refresh, voir ci-dessous.

![2017-04-12_19h39_25](https://cloud.githubusercontent.com/assets/355999/24971304/ce199dce-1fb7-11e7-8255-2731e4e8a423.png)

La gomme est disponible dans le menu à gauche, celui de la partie où apparaît le treeview. La gomme vise à : 

1. Vider le cache (localStorage) du navigateur.
2. Vider le cache serveur (la session associée à ton utilisation)

Le bouton refresh, à droite, concerne la note et en recharge une version fraîche (sans passer par le cache navigateur).  Ainsi, si tu as modifié le texte de ta note, le bouton refresh permet d'en récupérer une version à jour.

Refresh ne change pas le cache du browser pour les autres informations (autres notes vues ainsi que la liste des dossiers/fichiers).  Refresh ne concerne que la note affichée.

La gomme (=j'ai bien compris que l'icône n'est pas intuitive) vise à effacer le cache local et la session serveur.

Est-ce plus clair ? 

Bonne soirée.

**Comment by elecoest** [comment]
J'avais bien compris, juste que c'est pas intuitif la gomme

Le 12 avril 2017 à 19:43, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by cavo789** [comment]
Et moi qui écrit tout ce roman pour rien… :-D
