### ISSUE TITLE
Création des slides reveal 

### ISSUE THREAD

**Issue by chessman2212** [cavo789/marknotes#21]
Lors de la création des soldes, ce sont les balises h1,h2... qui créent les slides. Ceci ne prend pas en compte le fait d’utiliser directement le markdown pour visualiser les slides (comme le permet reveal). Possibilité d’ajouter une telle option ?

**Comment by chessman2212** [comment]
Oups erreur de clavier T9, je parle bien des slides

**Comment by cavo789** [comment]
Salut chessman

Peux-tu m'expliquer davantage s'il te plaît ? 

Marknotes prend un fichier .md en input; dans ce fichier, tu écris tes titres avec la notation # (titre 1), ## (titre 2), etc.

Marknotes prend ce fichier pour générer du code HTML qui est ensuite transmis à Reveal. Donc oui, c'est du code HTML qui est envoyé mais oui aussi, la syntaxe markdown est fonctionnelle.

Tu m'expliques un peu plus ton besoin ? 

Merci.

**Comment by chessman2212** [comment]
Reveal interprète nativement le markdown pour créer les slides avec la volée. Par exemple en suivant ce code : 
```

# Test attributes in Markdown
## Slide 1



## Slide 2
<!-- -- id="slide2" data-transition="zoom" data-background="#A0C66B" -->


## Slide 2.1
<!-- -- data-background="#ff0000" data-transition="fade" -->


## Slide 2.2
[Link to Slide2](#/slide2)



## Slide 3
<!-- -- data-transition="zoom" data-background="#C6916B" -->



## Slide 4

```
On obtient alors cette structure : 
Slide 1 | Slide 2   | Slide 3 | Slide 4
------  | Slide 2.1 | ------ | -----   
------  | Slide 2.2 | ------ | -----   

Du coup on peut organiser la navigation horizontal et vertical dans les slides reveal directement.

Je commence tout juste à m'approprié maronites, donc soit indulgent si la question semble bête :-)

**Comment by cavo789** [comment]
Salut Christophe

Je viens de copier ton code sur mon site de démo : https://www.marknotes.fr/docs/test-md-reveal.md

En mode reveal, cela donne ceci (il suffit de changer l'extension) : https://www.marknotes.fr/docs/test-md-reveal.reveal.

Le slideshow est donc ... parfait excepté que je n'ai pas de scroll vertical et c'est logique; il n'est pas encore programmé ;)

D'ailleurs, je ne sais pas encore comment je vais pouvoir programmer cela car, si je reprends ton code (je supprime les commentaires) :(

```markdown
# Test attributes in Markdown
## Slide 1
## Slide 2
## Slide 2.1
## Slide 2.2
[Link to Slide2](#/slide2)
## Slide 3
## Slide 4
```

j'ai donc un titre 1 et six titres 2; sept slides donc.

Ma conversion reveal me donne bien ces sept slides (mais horizontaux). À mes yeux, cela me paraît normal vu que ton code markdown proposé n'indique pas de verticalité (mais, je le répète, je ne l'ai pas programmé dans marknotes->reveal).

(Tu es certain de ta syntaxe pour la verticalité?)

**Comment by chessman2212** [comment]
Hello,
oui je suis certain de mon code. Et les lignes vides ont toutes leur importance car c'est en fonction du nombre de ligne que reveal crée un slide horizontal ou vertical. Cette page explique pas mal le fonctionnement : http://www.planet-libre.org/index.php?post_id=20878

D'ailleurs, sur la base de cet article, il serai en fait tout à fait possible de ne pas avoir à transposer le md en html pour le cas de reveal.

**Comment by cavo789** [comment]
Bonjour Christophe

Je viens de publier une nouvelle version de marknotes où j'ai introduis une option "no_html_convert" pour la fonctionnalité Reveal càd de donner la possibilité au webmaster de décider s'il faut ou non préalablement convertir en HTML avant affichage avec Reveal.

Cela se passe à peu près ici : https://github.com/cavo789/marknotes/blob/master/src/marknotes/plugins/content/slides/reveal.php#L270-L289

L'option se trouve dans settings.json.dist : https://github.com/cavo789/marknotes/blob/master/src/settings.json.dist#L155

On peut la surcharger en créant un fichier settings.json à la racine de ton site mais je l'ai aussi expliqué dans ma démo : https://www.marknotes.fr/docs/Reveal/no_html_convert/Markdown%20in%20Reveal.reveal

Note : perso, je préfère la conversion HTML parce qu'elle donne plus de puissance; entre autre la possibilité de mettre en forme les titres (usage de CSS), l'obtention d'URL plus sympa que #2 (numéro du slide) mais bien le ID du titre, etc.

Bonne journée.
