### ISSUE TITLE
v2 fails

### ISSUE THREAD

**Issue by mtompkins** [cavo789/marknotes#22]
Interesting looking project. Tried to install both by script and git clone. Unfortunately composer throws:

```
[Sat Dec 23 07:11:20.480367 2017] [php7:warn] [pid 541] [client ::1:55050] PHP Warning:  require(/srv/http/html/libs/composer/../guzzlehttp/promises/src/functions_include.php): failed to open stream: No such file or directory in /srv/http/html/libs/composer/autoload_real.php on line 66
[Sat Dec 23 07:11:20.480412 2017] [php7:error] [pid 541] [client ::1:55050] PHP Fatal error:  require(): Failed opening required '/srv/http/html/libs/composer/../guzzlehttp/promises/src/functions_include.php' (include_path='.:') in /srv/http/html/libs/composer/autoload_real.php on line 66
```

The guzzle folder is there in both cases, although in camelcase. Not sure if that helps.

**Comment by cavo789** [comment]
Hi

Sorry, I forgot to deeper analyze this.

The problem : the name of the folder /libs/guzzlehttp should be in lowercase. Please check your installation and correct the case if needed.

The origin : I'm working on Windows and there is no case sensitive problem with file/folder name. I've detect the problem on my first publish on a Linux site, rename the folder on my hard disk but it seems that github doesn't detect this change => doesn't update the repository.

I'll further analyze this.

So, for you : just rename /libs/GuzzleHttp to /ibs/guzzlehttp and it should be OK (please confirm)

**Comment by mtompkins** [comment]
Thx - had a feeling it was the camelcase and why I mentioned it. Will confirm at my first opp.

**Comment by cavo789** [comment]
Repository updated : the trick was to put fire `git config core.ignorecase false` in a command prompt.
I don't understand why, by default, it's not the case. 

*(But now GuzzleHttp is twice in my repository, need to find how to remove the camelcase version)*

**Comment by cavo789** [comment]
I close this issue; please come back if you can to give feedback.
