### ISSUE TITLE
v2 js error

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#23]
hello
after install v2 by installation script i have this error
```
marknotes.js:330 Uncaught TypeError: Cannot read property 'search_no_result' of undefined
    at initFiles (marknotes.js:330)
    at eval (eval at success (marknotes.js:228), <anonymous>:1:1)
    at Object.success (marknotes.js:228)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
initFiles @ marknotes.js:330
(anonymous) @ VM828:1
success @ marknotes.js:228
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
A @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
(anonymous) @ VM698:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
ajaxify @ marknotes.js:188
(anonymous) @ marknotes.js:77
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
```
any idea ?

**Comment by cavo789** [comment]
Salut Yannick.

Étrange car en ligne 330 du fichier /assets/js/marknotes, je n'ai rien de semblable. Tu viens de télécharger une v2 ? 

Je regarderai un peu plus tard dans la soirée en installant une v2 sur un site de test.

**Comment by micker** [comment]
oui c'est ca via l'installeur automatique

**Comment by cavo789** [comment]
Je viens d'installer une v2 sur un site de test en utilisant [marknotes_install](https://github.com/cavo789/marknotes_install) et je n'ai pas rencontré l'erreur que tu m'as mentionnée ci-dessus. Très étrange...

Pourrais-je avoir un accès à ton FTP si cela te convient ? Je regarderai alors...

Tu connais la procédure ;-) (https://send.aesecure.com)

Bonne soirée.

**Comment by micker** [comment]
bon re installer sur un autre hébergement c'est régler ...
