### ISSUE TITLE
Changer le logo

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#24]
Hello ce serait possible d'avoir une option pour changer le logo ?
Merki

**Comment by cavo789** [comment]
Via l'écran de configuration, je n'ai pas prévu cela pour l'instant (cet écran est fort récent, je l'ai codé il y a seulement quelques jours). Il n'est que partiel car il y a encore beaucoup d'autres options qui pourraient s'y trouver.

Toutefois pour le logo, je n'ai rien prévu pour le modifier via une configuation mais j'ai bien prévu de permettre de personnaliser totalement l'interface et donc, le logo. Voir "https://github.com/cavo789/marknotes/wiki/4.3-Use-yours-owns-templates" qui explique comment créer ton propre template.

Note : les informations dans le wiki concernent la version 1 de Marknotes; le wiki devra être remanié dans le futur.

Je note ta proposition comme suggestion d'ajout ;-)

**Comment by micker** [comment]
Merki

**Comment by cavo789** [comment]
Je trouvais l'idée sympa de pouvoir le faire depuis l'interface et comme c'était vraiment facile à faire...

Voilà, c'est programmé et sera disponible lorsque je ferais un merge de la branche **development** vers **master**.

Copie d'écran ci-dessous : 

![2018-01-05_08h31_18](https://user-images.githubusercontent.com/355999/34599499-f29e4362-f1f2-11e7-8dd4-2dfd195629cf.png)

Reste que si tu souhaites totalement adapter le look&feel de la page, tu peux surcharger le fichier /markntoes/templates/interface.php comme je l'ai expliqué plus haut.
