### ISSUE TITLE
L'option de theme n'est pas correctement affiché

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#25]
Hello dans la derniere version si on choisis black light, le changement est bien pris en compte mais quand on reviens dans l'administration dans la liste déroulante c'est toujour black par defaut
... une broutille

**Comment by cavo789** [comment]
Ah, cela n'aurait pas dû être le cas; je vais vérifier.

**Comment by cavo789** [comment]
Corrigé dans la branche **development**. Merci pour m'avoir remonté ce souci.

La correction sera disponible d'ici quelques jours lorsque j'aurais fusionné **development** et **master**.
