### ISSUE TITLE
Questions options

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#26]
Hello je decouvre l'outil en utilisation réelle voici quelques questions 
- quand on cache des options il semblerait qu c'est pour tout le monde même pour l'admin c'est normal ?
- c'est super les petits messages qui expliques que la configuration est sauvée mais comment rafraichir et bien voir les impacts ...

**Comment by cavo789** [comment]
* "Quand on cache des options" : tu parles de l'écran de configuration "ON / OFF" où on active / désactive des fonctionnalités ? Si on est sur la même longueur d'ondes, oui, c'est pour tout le monde.  Pourquoi crois-tu que cela ne serait que pour le "public" ? Un message, une phrase dans mon écran laisse croire que cela ne serait pas le cas ? 

On / Off, c'est pour tout le monde; il n'y a pas de distinction "public" / "admin" comme tu le connais en Joomla.

* La configuration est immédiatement sauvée dans le fichier settings.json qui est créé pour l'occasion à la racine de ton site web. Il suffit de faire CTRL-F5 (refresh) pour forcer l'application à se recharger et prendre en compte les nouveaux paramètres si ces derniers concernaient l'affichage.

**Comment by micker** [comment]
Oki .... Bon sur ma nouvelle installation j'ai un soucis de connexion je me connecte il me dis que c'est bon mais après je ne peu éditer ou renommer une note... Il me dis que je dois être connecté...

**Comment by micker** [comment]
ta une idée pour le login ?

**Comment by cavo789** [comment]
Je n'avais pas vu (évite d'utiliser une même issue pour des sujets différents, cela rends compliqué le suivi).

Je regarderai pour voir si je peux reproduire cela.

**Comment by cavo789** [comment]
Je viens de mettre à jour marknotes sur ton serveur; il est maintenant possible de changer de logo depuis l'écran des settings (je viens de mettre un logo que tu connais bien) et j'ai aussi, donc, corrigé le problème des listes déroulantes qui ne reprennaient pas, en sélectionné par défaut, la valeur actuelle. Corrigé donc.

Pour le souci du login, vérifie un peu quand tu en as le temps, j'ai aussi corrigé à ce niveau un bug dans la gestion de l'authentification qui se perdait à un moment précis.

**Comment by lafacenord** [comment]
D'abord merci ! C'est l'outil que je cherchais. Pour autant, je n'arrive pas à résoudre la question de l'accès aux notes et aux éventuels sous-dossiers créés pour les organiser. Je peux browser les dossiers et les notes quand je ne suis pas connectée, dès que je le suis, impossible d'ouvrir un dossier et donc les notes qu'il contient ! D'où vient l'erreur ?
