### ISSUE TITLE
probleme de md  â¦.md] doesn\'t exists

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#27]
Hello je ne sais pas pourquoi
il ne me trouve pas certaine note il met ce message

An error has occured :
Internal status: error
HTTP Status: 404 (Not Found)
XHR ReadyState: 4
Raw server response:
The note [/home/flexicck/public_html/documentation/docs/fr-FR/flexicontent/plugins/flexicontent_fields_extendedwe â¦.md] doesn\'t exists
alors que le fichier est bien ok a la bonne place ...=> flexicontent_fields_extendedweblink.md

**Comment by cavo789** [comment]
Le nom du fichier semble mal encodé. Tu écris "extendedwebblink.md" et le message mentionne "extendedw " suivi de caractères incorrects.

Je te suggère de le renommer sur le disque pour voir si cela corrige le souci d'encodage dans son nom.

**Comment by micker** [comment]
Je vais regarder ce qui est bizarre c'est que je généré les MD via le composant qui scan les ini de emanuel

**Comment by cavo789** [comment]
J'ai galéré "comme pas possible" dit-on en français avec la gestion des nom de fichiers possédant des accents jusqu'à me rendre compte il y a cinq jours que mes difficultés étaient consécutives à un bug de PHP 7.0 (https://github.com/php/php-src/blob/PHP-7.1.0beta2/UPGRADING#L321).

Depuis, j'ai décidé de cesser de trouver des "workarounds" et j'ai opté pour utiliser une librairie de gestion de fichiers qui propose surtout de ne plus se soucier de "où" sont stockés les notes : je peux les stocker sur Dropbox ou Amazon p.ex. et plus forcément dans le dossier /docs du site.

Le souci actuel : c'est très lent
La solution en cours de développement : je revois complètement la gestion du cache.

C'est la raison d'exister de la version "[development](https://github.com/cavo789/marknotes/tree/development)" de marknotes. Je travaille sur cette fonctionnalité qui, du coup, permettre de ne plus avoir de souci avec les noms de fichiers ayant des accents.

Note qu'il me faudra plusieurs jours pour réussir à finaliser cela; les impacts sont vraiment importants.

**Comment by cavo789** [comment]
Tiens, je n'ai pas pensé à te demander : quelle version de PHP utilises-tu sur ton site distant ? Si c'est PHP 7.0, peux-tu passer sur PHP 7.1 ou supérieur (quoique, vu que le fichier d'origine *lexicontent_fields_extendedweblink.md* ne contient pas d'accents, cela ne devrait pas être le problème).

**Comment by micker** [comment]
j'ai peut être une piste !
la longeur des fichier md
les fichier qui plantent a partir de 31 caractères ...
c'est possible ?

**Comment by cavo789** [comment]
Non, la longueur n'a rien à voir. 
Si ton site est sur internet, puis-je avoir un accès ? (https://send.aesecure.com)
Je regarderai alors directement sur le site.

**Comment by micker** [comment]
ok .... bizarre tout est dans le mail a+

**Comment by cavo789** [comment]
Tu avais raison, la longueur était la cause : à l'affichage dans le treeview, les noms longs sont abrégés avec un "..." et le code JS utilisait le texte affiché (et c'était une erreur de ma part) et non l'attribut data-url qui contient l'URL complète.

Je viens de corriger et la correction est déjà en place sur ton site. Cette issue est donc close mais, toutefois, j'ai vu que certains noms de fichiers (en allemand p.ex. contenaint des caractères comme ü pour le "für") et la gestion n'est pas correcte. Je regarde à résoudre ce nouveau problème d'accents.

**Comment by micker** [comment]
oki super !
