### ISSUE TITLE
ngnix error

### ISSUE THREAD

**Issue by vince2bir** [cavo789/marknotes#28]
Hi,

After installation on my nginx server, the loading fails with a 500 error.

In the log I have an error in /var/www/clients/client1/web19/web/marknotes/includes/initialize.php on line 250 because it looks for the settings.json.dist file in /var/www/clients/client1/web19/ instead of /var/www/clients/client1/web19/web/ (which is the root directory)

`		if (is_file($fname = dirname(self::$webRootFolder).DS.'settings.json.dist')) {`

**Comment by cavo789** [comment]
You're perfectly right ! Thank you for this valuable information.

The correct line should be

```php
if (is_file($fname = self::$webRootFolder.'settings.json.dist')) {
```

I've patched the file and push it to the repository.

Thanks @vince2bir

**Comment by vince2bir** [comment]
There seems to be the same trouble in libs/league/flysystem/src/Adapter/Local.php
line 76 `  $root = is_link($root) ? realpath($root) : $root;`

**Comment by cavo789** [comment]
For flysystem I can't do nothing, it's an external library... https://github.com/thephpleague/flysystem

Do you know if it's possible to install a nginx server locally on a Windows OS ? I've never see that.

I'm currently using Wamp (and EasyPHP sometimes) and I don't have problem with filepaths, it seems that nginx is more strict.

**Comment by cavo789** [comment]
Ok, simple to find and install (http://nginx.org/en).
I can display basic html file but .php isn't interpreted by downloaded. Seems that I'll need to read the manual...

**Comment by vince2bir** [comment]
I moved Marknotes to a subdirectory and I have no error anymore (was due to an opendirectory restriction). Although, it's not a fix, it's a work around.
I know have to deal with the rewrite rules.

**Comment by cavo789** [comment]
I'll test on a Apache site after applying openbase_dir restriction to test that.

Marknotes is working both on my server on a root folder and subfolder too. Not tested yet with the restriction.

Have a nice day !
