### ISSUE TITLE
Perte d'accès à l'identification

### ISSUE THREAD

**Issue by lafacenord** [cavo789/marknotes#29]
D'abord merci ! C'est l'outil que je cherchais. Pour autant, je n'arrive pas à résoudre la question de l'accès aux notes et aux éventuels sous-dossiers créés pour les organiser. Je peux browser les dossiers et les notes quand je ne suis pas connectée, dès que je le suis, impossible d'ouvrir un dossier et donc les notes qu'il contient ! D'où vient l'erreur ?

**Comment by cavo789** [comment]
Bonsoir

Que je comprenne bien le souci : tu peux voir les notes, parcourir les dossiers, ... en mode public mais si tu es connecté, tu ne peux plus ? 

Je viens de tester le site https://www.marknotes.fr/ qui contient toujours la toute dernière version du logiciel (mise-à-jour automatisée) et je ne rencontre pas le souci.

Peux-tu me donner plus d'infos car je ne suis pas certain de comprendre ?

**Comment by lafacenord** [comment]
C'est tout à fait ça :  je n'accède pas aux dossiers si je suis connectée.

Pour préciser un peu, j'ai refait une install propre cet après-midi avec la dernière version. Jusqu'à présent, je n'ai travaillé qu'en local et je n'avais pas besoin d'un accès en écriture. C'est en testant l'accès connecté (en local) en vue d'héberger le service ailleurs que je me suis aperçue du dysfonctionnement (avec la version précédente comme avec la dernière).

**Comment by cavo789** [comment]
Je ne suis toujours pas sûr de comprendre...

L'accès aux notes (dossiers / fichiers) ne devrait pas être impacté par le fait que tu sois connecté ou pas (mais bien, évidemment, l'accès en mode édition).

Je dois rater quelque chose je pense.

Peux-tu me communiquer l'URL de ton site marknotes (s'il est accessible en ligne) et peut-être pourrais-tu remettre le login et le mot de passe par défaut le temps que j'y jette un oeil.

**Comment by lafacenord** [comment]
Pour l'instant, je n'ai rien en ligne. Mais je viens d'identifier la cause du problème : Chrome ! Le mode connecté fonctionne parfaitement avec Firefox. Marknotes n'est pas du tout en cause ! Toutes mes excuses pour cette fausse alerte. 
Chrome devient lentement inutilisable... du site des impôts à l'authentification cas en passant donc par Marknotes...

**Comment by cavo789** [comment]
Tant mieux pour marknotes mais j'utilise Chrome quotidiennement et je ne rencontre pas le problème que tu mentionnes ici (et que j'ai du mal à "traduire" ne voyant pas une source d'un tel problème).

Bon, si c'est résolu car non lié à Marknotes; je ferme donc cette issue.

Bonne soirée.
