### ISSUE TITLE
désactiver DataTables ?

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#3]
Hello,

C'est possible de désactiver  le datatable dans les paramètres ?

Dans mes rendu html, je n'en ai pas besoin.

Merci

**Comment by cavo789** [comment]
Salut

Fais une surcharge du fichier templates/screen.php et supprime le css (https://github.com/cavo789/marknotes/blob/master/src/templates/screen.php#L60) et les js (https://github.com/cavo789/marknotes/blob/master/src/templates/screen.php#L168-L169).

Cela devrait être suffisant.

**Comment by elecoest** [comment]
OK c'est fait. je t'en fait une autre ^^
