### ISSUE TITLE
impossible de modifier une note

### ISSUE THREAD

**Issue by augras** [cavo789/marknotes#31]
Bonjour,
Je découvre MarkNotes, bravo pour tout ce travail, mais rencontre quelques soucis.
Je peux créer une nouvelle note, y inscrire quelque chose, mais dès que je l'ai enregistrée une première fois impssible de faire la moindre modification !
L'erreur est très similaire à la #27 mais différente car pas du tout de caractère accentué et surtout le nom du fichier n'apparaît pas :
An error has occured :
Internal status: error
HTTP Status: 404 (Not Found)
XHR ReadyState: 4
Raw server response:
The file [/home/augras/public_html/augras.eu/marknotes/docs/.md] doesn\'t exists
Quel que soit le nom du fichier j'ai toujours ce résultat.
Je suis en version 7.2 de php (j'ai essayé de 7.0 à 7.2).
Merci,
Philippe

**Comment by cavo789** [comment]
Bonjour Augras

Désolé pour ce bug.

Le nom de la note semble non connu (`marknotes/docs/.md`) ce qui devrait être impossible.

Au moment où tu as créé ta note, comment as-tu procédé s'il te plaît ? 

Est-ce : 

1. Tu t'es connecté dans l'interface
2. Tu as cliqué sur un dossier de l'arborescence avec clic droit puis Nouvelle note
3. Tu as donné un nom à la note (quel nom s'il te plaît ?)
4. La note a été affichée et mode édition

J'aimerai bien comprendre comment tu as créé la note et surtout le nom que tu es donné.

Tu dis avec tester plusieurs noms donc, même un simple "Test" ne fonctionnerait pas ? 

Bonne soirée

**Comment by augras** [comment]
Bonjour cavo789,
Pas d'inquiétude : je teste et rien de critique.
1 oui
2 oui
3 oui, test/essai/Essai que des noms très simples sans accents, rien de spécial : pas de soucis à ce niveau
4 oui : et là je peux utiliser et enregistrer... mais dès que j'ai enregistré une fois c'est foutu !
J'ai pensé à un problème de droits mais ce n'est pas ça.
Si tu veux je créé un utilisateur ftp sur mon dossier maknotes et tu fais ce que tu veux avec pour essayer de comprendre.
J'ai supprimé et réinstallé plusieurs fois y compris en laissant tout en anglais, on ne sait jamais... rien à faire. Le pire hier soir ça semblait vouloir fonctionner, je paramètre toute une configuration en français avec tous les modules voulus et après être sorti de la page de configuration page blanche et impossible d'avoir autre chose sauf à supprimer le fichier de conf généré !
J'étais passé en php7.2 mais à cause d'effets de bord sur mon forum j'ai dû repasser en 7.1.
Philippe

**Comment by cavo789** [comment]
>Si tu veux je créé un utilisateur ftp sur mon dossier maknotes et tu fais ce que 
>tu veux avec pour essayer de comprendre.

Oui, je veux bien car je ne parviens pas à reproduire le souci sur ma machine et mon site de test.

Tu peux m'envoyer les données au travers de mon interface sécurisée https://send.aesecure.com (il faudra m'envoyer l'URL qui sera alors générée par email mais tout est expliqué).

Et ensuite je tâche de faire au plus rapide.

Bonne journée.

**Comment by augras** [comment]
Bonjour Christophe,
Je viens de faire le nécessaire.
Mais je t'assure qu'"il n'y a pas d'urgence.
Merci,
Philippe

**Comment by augras** [comment]
Précision pour reproduire le problème de non modification : après la création d'une note je peux modifier la note tout en ayant enregistré plusieurs fois tant que je n'ai pas affiché une autre note ou quitté explicitement en cliquant sur exit editing mode ; si je reviens sur une note après l'avoir quittée ou affichée aune autre impossible de modifier.
philippe

25 mai 2018 11:03 "Christophe Avonture" <notifications@github.com (mailto:notifications@github.com?to=%22Christophe%20Avonture%22%20<notifications@github.com>)> a écrit:
	Bonjour Philippe 

	Je me suis connecté sur ton site ce matin et j'ai fait différents tests qui ne m'ont pas permis de provoquer le bug. Puis, un peu par hasard, je pense l'avoir compris : je suis trop formaté càd que lorsque je crée une note, je clique toujours sur le dossier qui va reprendre la note et jamais sur une note de ce dossier. 

	Ci-dessous une image pour illustrer ce que je pense être l'origine du bug : 

	 (https://user-images.githubusercontent.com/355999/40535871-abcd4704-600a-11e8-9078-e139723a5e00.png) 

	Au lieu de cliquer sur le dossier /docs (puisque c'est là que je vais créer ma nouvelle note), j'ai cliqué sur une note existante puis "Nouvelle note" et là, oui, j'avais un bug car le "parent.path" n'était pas valide (j'obtenais undefined car cette notion n'existe que pour les dossiers). 

	Je viens de patcher la version du script .js sur ton site et cela donne les résultats escomptés : je peux maintenant faire ce que l'image ci-dessus montre. On peut faire un clic droit sur une note puis "Nouvelle note" et la note se crée alors dans le même dossier. 

	Peux-tu s'il te plaît voir si ce patch (donc déjà en production sur ton site; tu n'as rien à installer) résouds le bug que tu rencontrais ? Si oui, je passe alors ma modification en prod sur le dépôt GitHub. 

	Merci et bonne journée.

**Comment by augras** [comment]
reBonjour Christophe,
merci encore pour tes démarches. 

	Mais je n'arrive toujours pas modifier une note : c'est bien un problème de modification que j'avais pas de création. J'ai créé 3 ou 4 nouvelles notes sans soucis, soit par clic sur un dossier, soit sur une note et impossible de les modifier après avoir enregistré une première fois et maintenant également impossible d'en créer de nouvelles en cliquant droit sur un dossier ... très étrange, je peux toujours en cliquant droit sur une note... sans pour autant pouvoir la modifier après un premier enregistrement.
Je suis bien clair ? ça l'ai pour moi mais peut-être pas pour toi !
Tu peux m'appeler ci-besoin au 0555456619 : je ne suis pas toujours dans mon bureau mais assez souvent tout de même. 

	Tu as raison : je cliquais droit sur une note pour en créer une nouvelle... j'aurai dû être plus précis
Désolé pour ces tracas
philippe

25 mai 2018 11:03 "Christophe Avonture" <notifications@github.com (mailto:notifications@github.com?to=%22Christophe%20Avonture%22%20<notifications@github.com>)> a écrit: 
	Bonjour Philippe 

	Je me suis connecté sur ton site ce matin et j'ai fait différents tests qui ne m'ont pas permis de provoquer le bug. Puis, un peu par hasard, je pense l'avoir compris : je suis trop formaté càd que lorsque je crée une note, je clique toujours sur le dossier qui va reprendre la note et jamais sur une note de ce dossier. 

	Ci-dessous une image pour illustrer ce que je pense être l'origine du bug : 

	 (https://user-images.githubusercontent.com/355999/40535871-abcd4704-600a-11e8-9078-e139723a5e00.png) 

	Au lieu de cliquer sur le dossier /docs (puisque c'est là que je vais créer ma nouvelle note), j'ai cliqué sur une note existante puis "Nouvelle note" et là, oui, j'avais un bug car le "parent.path" n'était pas valide (j'obtenais undefined car cette notion n'existe que pour les dossiers). 

	Je viens de patcher la version du script .js sur ton site et cela donne les résultats escomptés : je peux maintenant faire ce que l'image ci-dessus montre. On peut faire un clic droit sur une note puis "Nouvelle note" et la note se crée alors dans le même dossier. 

	Peux-tu s'il te plaît voir si ce patch (donc déjà en production sur ton site; tu n'as rien à installer) résouds le bug que tu rencontrais ? Si oui, je passe alors ma modification en prod sur le dépôt GitHub. 

	Merci et bonne journée.

**Comment by cavo789** [comment]
Je pense que c'est bon (patch en place sur ton site).

Le souci : le bouton Edit (en haut à droite) était bien fonctionnel, il fait un appel à un code javascript en lui transmettant un objet (dont une des propriétés est le nom du fichier).

En faisant un clic droit depuis l'arborescence, puis Edit depuis le menu contextuel, ce n'était pas un objet qui était passé mais juste le nom du fichier => le bouton Save ne recevait pas ce qu'il lui fallait pour correctement initialiser la tâche ajax de sauvegarde => le cadre rouge.

Je viens de patcher ton site et en principe, cette fois, le bug est bien identifié et solutionné.

Peux-tu me le confirmer s'il te plaît ? 

Bonne journée.

**Comment by augras** [comment]
YES !
ça fonctionne : MERCI.
Mais sur les anciennes notes que j'édite il y a systématiquement
---
title: New
created_time: '2018-05-24 08:29:58'
language: en
subtitle: ''---

qui s'ajoute au début de la note, autant de fois que d'édition : 3 éditions= 3 fois ce texte qui est parfaitement visible quand on affiche la note normalement. 

	ça n'a pas l'air de le faire sur les nouvelles notes, seulement sur les anciennes : dans le cas présent pas de soucis puisque test.

Par contre je ne peux pas créer de notes en cliquant droit sur un dossier existant : rien ne se passe quand je clique sur créer une nouvelle note !
Je peux créer un nouveau dossier, puis créer une nouvelle note dedans en cliquant droit sur le dossier : mais c'est la seule ; pas possible d'en créer d'autres !

Décidément pas facile !

Je reçois tes messages alternativement sur mon adresse perso philippe.augras@libertysurf.fr et sur mon adresse pro philippe.augras@culture.gouv.fr (j'ai transmis les infos pour la connexion ftp de mon boulot) : il vaut mieux utiliser la perso car je ne vais pas tarder à partir.

Merci encore,

Philippe

25 mai 2018 14:20 "Christophe Avonture" <notifications@github.com (mailto:notifications@github.com?to=%22Christophe%20Avonture%22%20<notifications@github.com>)> a écrit: 
	Je pense que c'est bon (patch en place sur ton site). 

	Le souci : le bouton Edit (en haut à droite) était bien fonctionnel, il fait un appel à un code javascript en lui transmettant un objet (dont une des propriétés est le nom du fichier). 

	En faisant un clic droit depuis l'arborescence, puis Edit depuis le menu contextuel, ce n'était pas un objet qui était passé mais juste le nom du fichier => le bouton Save ne recevait pas ce qu'il lui fallait pour correctement initialiser la tâche ajax de sauvegarde => le cadre rouge. 

	Je viens de patcher ton site et en principe, cette fois, le bug est bien identifié et solutionné. 

	Peux-tu me le confirmer s'il te plaît ? 

	Bonne journée.

**Comment by augras** [comment]
Je crois avoir compris pourquoi je ne pouvais créer qu'une seule note : je créais une note sans changer son nom par défaut ! Quand je voulais en créer une nouvelle, par défaut elle avait le même nom que la précédente... et rien ne se passait.
En renommant systématiquement une nouvelle note créée plus de soucis.
Je ne sais pas si tu as déjà modifié quelque chose en tout cas actuellement ça fonctionne comme dit ci-dessus.
Si ça te dit de conserver cette espace à titre de tests je peux te le laisser : je vais faire une installation dans un autre dossier. Il y a actuellement 100 mo de quota mais je peux l'augmenter. Et comme j'ai le chic pour tomber sur des trucs qui n'arrivent qu'à moi je pourrai tester en direct !
Un grand merci pour ton application et tout le temps consacré à résoudre mes problèmes.
Philippe

**Comment by cavo789** [comment]
Salut Philippe

Je revenais sur cette page pour continuer et ... YES, donc, tout semble OK pour toi.

Le bug m'aura donné du fil à retordre aujourd'hui, il n'était pas simple à dénicher mais bonne chose de faite donc.

Merci pour tes retours et l'accès à ton site.

Vu que ton problème est résolu, je n'ai plus besoin de conserver un accès au FTP, n'hésite pas à désactiver mon compte.

Je te souhaite une bonne soirée et bon amusement avec Marknotes.

**Comment by augras** [comment]
Merci encore.
Je crois que je vais bien m'amuser effectivement.
Philippe

**Comment by cavo789** [comment]
Welcome !

Je me permets donc de clôturer cette issue. N'hésite pas, si besoin, d'en ouvrir une autre.
