### ISSUE TITLE
les images ne s'upload pas

### ISSUE THREAD

**Issue by augras** [cavo789/marknotes#32]
reBonjour,
Il y a deux façons de mettre une image : 
- avec un lien et là ça fonctionne ;
- en uploadant le fichier via l'interface... et là ça ne fonctionne pas !
Les fichiers apparaissent bien dans la partie de téléchargement et je vois pour chaque fichier une petite boite de progression et tout semble se passer correctement... mais les fichiers ne s'affichent dans la note et après vérification ils ne sont pas dans .images. Si je les upload "à la main" ça fonctionne.
Enfin pas tout à fait car le lien mis automatiquement %URL% doit être remplacé par le chemin complet pour que ça fonctionne.
Merci,
Philippe

**Comment by cavo789** [comment]
Je viens de tester sur mon localhost et en déposant une image (un fichier .png) j'ai reçu une erreur serveur 500; je vais devoir analyser cela. Ces prochains jours, c'est un peu compliqué car j'ai vraiment beaucoup à faire, je vais tacher de faire au plus vite.

Bonne soirée.

**Comment by augras** [comment]
Pas d'inquiétude : je ne suis pas pressé.
Ton outil me plait vraiment beaucoup mais je n'ai pas d'urgence.
"Content" finalement que ça ne soit pas que moi.
Philippe

**Comment by cavo789** [comment]
Bonjour Philippe

Patch déployé.

Le problème se situait dans le fichier qui transfère l'image depuis le dossier tmp (après upload) et qui devait déplacer l'image vers sa destination. Le chemin du dossier cible était mal construit sur Unix (mais bon sur ma machine Windows).

Merci pour avoir remonté l'info.
