### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Aisyk** [cavo789/marknotes#33]
Bonjour,

J'ai installé comme indiqué marknotes. J'ai téléchargé le fichier install.php, lancé l'installation. Lors de l'installation, marknote m'a indiqué qu'il ne pouvait pas télécharger le dossier et qu'il fallait que je copie le contenu du git avec filezilla.

Je me retrouve avec une installation "demo" où je n'ai jamais eu à rentrer de mot de passe ni de compte administrateur.
http://interventions-numeriques.fr/Notes/

Je souhaite une installation comme indiquée dans la présentation. Comment faire ?
Je suis sur un hébergement OVH, avec PHP 7.0 activé.

Merci.

**Comment by cavo789** [comment]
Bonjour

Rapide accès sur votre site, cela semble fonctionnel.

Si l'installateur n'a pas fonctionné, probablement la configuration du serveur n'a pas permis de télécharger le fichier (il faut que curl soit actif) et il faut permettre de dézipper le fichier (là encore un module qui doit être actif sur votre hébergeur). Donc, oui, il y a des situations où l'installateur ne peut pas fonctionner.

Pour l'installation manuelle, cela semble donc fonctionnel.

Pour le login et mot de passe, oui, je me disais aussi qu'il faut que je rende cela plus explicite. TODO Christophe.

Le login par défaut est **admin** et le mot de passe **marknotes**. Il est repris dans le fichier settings.json.dist (c'est expliqué ici : https://github.com/cavo789/marknotes/wiki/4.1-Define-yours-preferences).

Une fois connecté, affiche la fenêtre des paramètres (bouton Settings en haut à droite puis personnaliser les paramètres de Marknotes). Et là, tu peux initialiser le login / password à celui de ton choix.

Est-ce que cela réponds à ta question ? 

Bonne journée.

**Comment by Aisyk** [comment]
Bonjour,

Cela répond en partie à mes questions.
J'ai bien pu me connecter en admin, mais je n'ai pas de possibilité de personnaliser le compte admin

Voir les captures : 
https://framapic.org/ZSlwvoj881ap/nl9bisK9QDoR.png
ET
https://framapic.org/hcQdY9y2QBy7/sSoaDNNxSnOH.png

**Comment by cavo789** [comment]
Sur ta première capture (https://framapic.org/ZSlwvoj881ap/nl9bisK9QDoR.png), clique sur le lien 'Update application's settings' (le dernier).

Un formulaire va s'afficher avec les trois cent paramètres éditables de Marknotes.

Voir 5. Authentication.

**Comment by Aisyk** [comment]
Ok,

Merci, je suis sur le bon endroit. C'est pas évident à comprendre comme nom "update" pour éditer des préférences...

Merci.

**Comment by cavo789** [comment]
Cet écran permet de franciser l'interface... 

Si vous avez la moindre idée d'amélioration n'hésitez pas à m'en suggérer. 

Je ferme donc ce sujet.

Bonne journée.

**Comment by cavo789** [comment]
Pour info, je viens de modifier la note d'introduction pour qu'elle soit plus explicite sur ce sujet : 

![2018-05-25_15h01_02](https://user-images.githubusercontent.com/355999/40545565-8dced98a-602c-11e8-920e-b6b32d57f98e.png)
