### ISSUE TITLE
Créer une nouvelle note

### ISSUE THREAD

**Issue by Aisyk** [cavo789/marknotes#34]
Bonjour,

Plus qu'une issue, ce serait plutôt des suggestions au niveau de l'interface par défaut.
J'ai dû chercher longtemps avant de savoir créer une note et cela ,m'a donné quelques réflexions : 

* il faudrait un bouton "créer une nouvelle note", car naturellement, je vais dans les icônes à droite pour essayer de créer quelque chose, et en fait, ce sont des options d'export.
* quand je clique sur une nouvelle note, je ne sais pas où chercher pour l'éditer... (l'icone dans le menu est peu visible. Dans certains autres logiciels, ce type d'icône est directement intégré avant ou après le titre d'un document)
* j'ai placé un document en .md dans le dossier à partir de filezilla, il est nécessaire d'actualiser le navigateur pour qu'il soit visible.
* le mot de passe en clair dans l'interface et dans les fichiers de configuration.
* l'icône pour lancer le gestionnaire de fichiers devrait plus être à côté de l'arborescence à gauche.
* dans les options de configuration, je ne comprend pas la différence entre "Show" et "Add"... si je le vois c'est qu'il est ajouté, et si je l'ajoute c'est que je veux le voir...
* il faudrait un menu pour configurer la barre de raccourcis, pour le moment c'est un concept "Quickicon"
* pourquoi intégrer Gogole Analytic et pourquoi pas plutôt Piwik ou d'autres solutions libres ?

Voilà ;)
Merci encore pour ce bel outil !

**Comment by cavo789** [comment]
Quelques éléments de réponse. Merci pour les idées.

```
J'ai dû chercher longtemps avant de savoir créer une note
```

Oui, je le comprends car tu as cherché longtemps afin de trouver le login / mot de passe. Entretemps, de mon côté, j'ai rendu cela plus évident au niveau de l'interface.

![2018-05-25_15h01_02](https://user-images.githubusercontent.com/355999/40550229-d1f8f1b0-6039-11e8-8555-76e8d9d0fcdb.png)

```
il faudrait un bouton "créer une nouvelle note", car naturellement, je vais dans les icônes à droite pour essayer de créer quelque chose, et en fait, ce sont des options d'export.
```

Oui mais difficile en l'état : pour savoir dans quel dossier je devrais créer la note, il faudrait que j'affiche un popup "Veuillez sélectionner le dossier de destination". Aujourd'hui, tel que je l'ai implémenté, c'est immédiat : tu fais un clic droit sur le dossier cible depuis l'arborescence et du coup, je sais immédiatement que c'est là-bas qu'il faut créer la note. Disons que la solution actuelle est la plus facile à implémenter surtout que, pour éditer une note, tu auras vite fait de découvrir le clic droit ;)

```
quand je clique sur une nouvelle note, je ne sais pas où chercher pour l'éditer... (l'icone dans le menu est peu visible. Dans certains autres logiciels, ce type d'icône est directement intégré avant ou après le titre d'un document)
```

Ok, j'entends ce que tu dis... Je tâcherai de trouver une astuce.
Pour le bouton "peu visible" là je ne comprends pas : le bouton (en haut à droite) à la même taille que tous les autres boutons. Trop petit ? Un petit coup de CSS ferait l'affaire mais il peut y avoir beaucoup de boutons ("zone QuickIcons") aussi cela risque d'occuper trop de place à l'écran.

```
j'ai placé un document en .md dans le dossier à partir de filezilla, il est nécessaire d'actualiser le navigateur pour qu'il soit visible.
```

Oui .. forcément. Tu es dans une page Web; pour que ton navigateur puisse détecter un nouveau fichier déposé par FTP, il faut rafraîchir ... ou je devrais toutes les XX secondes faire une tâche ajax pour scanner tous les dossiers de ton dossiers /docs (j'ai plus de 1.000 notes sur l'un de mes sites). Ce serait vraiment très lent.

Non, ici, zéro solution en vue. Cela me semble impossible.

```
le mot de passe en clair dans l'interface et dans les fichiers de configuration.
```

Oui parce que c'est un fichier .json et qu'il est éditable.
Je pourrais le crypter; bien sûr mais l'idée était que le .json soit éditable et personnalisable par d'autres interfaces.

Note que le fichier est protégé : tu ne peux pas y accéder par URL, tu aurais un access denied 403.

Donc, oui, en clair mais en principe impossible à accéder hormis par un script ayant accès à ton FTP.

```
l'icône pour lancer le gestionnaire de fichiers devrait plus être à côté de l'arborescence à gauche.
```

Dans une précédente version de Marknotes, j'avais des boutons à gauche et à droite, c'est un peu "Mais où chercher tel bouton". J'ai pris le parti de tout mettre à droite.

```
dans les options de configuration, je ne comprend pas la différence entre "Show" et "Add"... si je le vois c'est qu'il est ajouté, et si je l'ajoute c'est que je veux le voir...
```

Tu parles de p.ex. "Add the export to .pdf button to the QuickIcons area " ? Il y a une grosse différence.
"Show" : tu permets qu'on voit le bouton dans l'interface (=> tu actives la fonctionnalité)
"Add" : tu souhaites que le bouton soit immédiatement accessible dans l'écran principal, dans la zone nommée "QuickIcons" càd les boutons en haut à droite.

Tu peux donc avoir des boutons "Show" qui apparaissent que tu affiches les fonctionnalités en cliquant sur le bouton "Settings" en haut à l'extrême droite (càd dans le menu sur fond noir). 
"Add quickIcons" : tu veux que ce bouton soit en accès direct. 
C'est bien deux choses complètement différentes ;-)

```
il faudrait un menu pour configurer la barre de raccourcis, pour le moment c'est un concept "Quickicon"
```

Pas compris. C'est exactement le "Add to quickicons" que je propose, non ? 

```
pourquoi intégrer Gogole Analytic et pourquoi pas plutôt Piwik ou d'autres solutions libres ?
```

Parce que j'ai implémenté cette fonction Google Analytics pour des personnes qui avaient ce besoin précis ;) Moi, perso, je ne traque jamais mes utilisateurs.

```
Merci encore pour ce bel outil !
```

Merci pour tes retours.

Bonne soirée et bon week-end.
