### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by augras** [cavo789/marknotes#35]
Bonjour Christophe,
Ne t'inquiète pas je n'ai rien cassé ni rien trouvé de louche !
Mais je prends goût à Marknotes et je me dis qu'il serait plutôt intéressant de pouvoir simplement joindre des fichiers à une note : fichiers de tous formats. Quand on lit une note, il y a, un peu comme dans une messagerie, des pièces jointes et quand on clique sur un fichier il est téléchargé pour être ouvert avec le logiciel adéquat présent sur la machine. C'est quelque chose qui sur le coup me manque et me semble avoir un intérêt général pour tous les utilisateurs.
Par ailleurs j'utilise wallabag et shaarli : je pense que tu connais mais au cas où j'explique. Wallabag permet de stocker des pages web/articles et donc de toujours les avoir sous le coude même si le site n'est plus accessible ou simplement que l'article a été retiré. Shaarli permet de stocker tous les signets/favoris internet et permet également de faire des notes, mais beaucoup moins bien que Marknotes. Et je me dis que tout ça c'est très bien mais que un tout en un serait parfait.
Voilà pour les suggestions du jour.
Bon week-end,
Philippe

**Comment by cavo789** [comment]
Bonjour 

Marknotes propose déjà cela sous forme de plugin. En l'occurrence le plugin %LISTFILES%. c'est un plugin de type markdown. 

Une doc avec exemple se trouve sur mon site https://www.marknotes.fr/docs/marknotes/Plugins/markdown/listfiles.html 

Voir marknotes.fr pour d'autres plugins 😉 

J'espère que cela répondra à ton besoin. 

Bonne journée

**Comment by augras** [comment]
Merci pour ce retour très rapide.
Effectivement ce plugin permet de lister les fichiers dans un dossier : je n'avais même pas cherché si un plugin existait.
Mais pour créer le dossier et déposer les fichiers tout se passe via ftp ?
Philippe

**Comment by cavo789** [comment]
Par FTP ou par le gestionnaire de fichiers intégré à marknotes.il apparaît dans le menu settings une fois connecté.

Perso je nomme ce dossier avec un point comme premier caractère (ex .files) afin que le dossier n'apparaisse pas dans l'arborescence de marknotes.

**Comment by augras** [comment]
Oui, le gestionnaire de fichiers : je me suis contenté de l'ouvrir pour le moment.
Du coup ça couvre mon besoin.
Je suis en train de parcourir ta doc sur les plugins : en fait ils sont tous présents dans Marknotes et il y a juste à les activer et éventuellement les configurer ?
Il y a des plugins type wallabag et shaarli ?
Bonne journée,
Philippe

**Comment by cavo789** [comment]
La plupart des plugins sont déjà activés, rare sont ceux ne l'étant pas. Tu peux les voir dans l'écran des paramètres. Ils sont tous activables ou pas, aucun n'est obligatoire.

**Comment by augras** [comment]
Merci Christophe,
je regarde tous cela après avoir mis un fichier .htpassword sur mon accès.
Bon week-end,
Philippe

**Comment by augras** [comment]
Bonjour Christophe,
Alors avec le plugin on arrive effectivement à faire ce que je souhaite... mais c'est pas des plus ergonomique !
Dans l'idéal un bouton du type de celui pour joindre des images avec upload direct au bon endroit et listage des fichiers serait bien plus convivial. Fichiers uploadés automatiquement dans un dossier du même nom que la note mais avec un . devant pour le cacher.
C'est une suggestion d'amélioration : le plugin permet d'arriver au but "à la main".
Bonne journée,
Philippe

**Comment by augras** [comment]
Pas de soucis ! C'est une suggestion. Marknotes est déjà vraiment très fonctionnel et c'est déjà très sympathique de le partager.
Merci de garder l'idée dans un coin.
Bonne journée,
Philippe

**Comment by cavo789** [comment]
Merci; oui, idée ayant été rajoutée à la longue liste ;-)

Pour info, ce week-end j'ai développé un nouveau petit truc : archivages des précédentes version d'une note éditée.

![2018-05-28_10h47_49](https://user-images.githubusercontent.com/355999/40610900-787cb0da-6274-11e8-9e00-af5c7dfd9824.png)

L'idée (et le besoin) : si jamais l'utilisateur sauve une note et puis, oh zut, j'ai fait une bétise... ou encore qu'une personne édite une note et qu'une seconde personne (autre ordinateur) édite la même note : la version affichée par les deux est la même. Une personne modifie et sauve... Le second modifie et sauve : les modifs. du premier seraient perdus car marknotes n'est pas prévu pour gérer une concurrence des accès. D'où besoin, au minimum, de conserver l'état d'une note avant qu'elle soit modifiée.

(Au fûr et à mesure, le logiciel s'enrichit donc de fonctionnalités ;-) )

**Comment by augras** [comment]
Bonjour Christophe,
C'est un plugin important !
Question : il garde toutes les versions ou se contente de la dernière ?
Bonne journée,
Philippe

**Comment by cavo789** [comment]
Non pas cette fois car la fonctionnalité markdown.write est native (et essentielle). J'ai donc juste ajouté un paramètre dans l'écran de configuration pour activer / désactiver l'archivage et le code est en quelques lignes de programmation. Mais oui, cela aurait pû être un plugin se greffant sur l'évènement "markdown.write".

Pour l'instant, je n'ai pas prévu de faire un "ne conserver que les xxx derniers" (je garde tout) mais c'est vrai qu'il faudrait que  j'envisage cela, oui, c'est juste.

**Comment by augras** [comment]
Je viens de mettre à jour : merci pour cette façon vraiment simple de mettre à jour.
Et j'ai vu la fonctionnalité apparaître.
Disons qu'avec tous les fichiers conservés on est juste limité par l'espace disque... étant chez un hébergeur tout illimité ça n'est pas problématique ; sinon il faut aller faire le ménage de temps en temps.

**Comment by cavo789** [comment]
Oui absolument maintenant ce ne sont jamais que des .md : la taille d'un tel fichier n'est jamais très grande. J'ai près de 2 000 .md sur mon disque (notes principales) et ce n'est pas ces fichiers-là qui prennent de la place mais bien les images, fichiers joints tels que .pdf, etc.  La fonctionnalité archivage n'en est qu'à ses débuts; next step p.ex. permettre de restaurer une archive depuis l'éditeur.

Bonne journée.
