### ISSUE TITLE
impossible de se connecter

### ISSUE THREAD

**Issue by augras** [cavo789/marknotes#36]
Bonjour Christophe,
Je n'ai pas retouché à Marknotes depuis lundi après la mise à jour et ce matin impossible de me connecter.
A priori la maj n'a rien à voir avec ça car je me souviens parfaitement m'être connecté après pour vérifier que ton option supplémentaire de backup des fichiers avant modification était bien présente.
Toujours est-il que ce matin après validation de l'identifiant/mot de passe et bien rien ne se passe : je ne suis pas connecté, aucun message... écran identique sans possibilité d'édition.
Je n'ai pas un accès plein via ftp de mon boulot mais j'ai pu vérifier que le mot de passe était bien le bon dans le fichier settings.json, le fichier settings.dist.json contenant toujours le mot de passe par défaut.
Bonne journée,
Philippe

**Comment by augras** [comment]
En fait il y a des avertissement dans l'onglet css uniquement : le reste est vide en dehors de réseau.

**Comment by cavo789** [comment]
L'erreur était le nom de la fonction appelée lorsqu'on cliquait sur le bouton "Login" dans le popup  : ce même nom était réutilisé dans l'écran de restriction de dossier pour la recherche => deux fois le même nom, JS n'aime pas trop ça.

Vu qu'il n'est pas possible de te connecter dans ta version actuelle, impossible d'afficher l'écran de téléchargement ==> récupère le fichier install.php depuis https://github.com/cavo789/marknotes_install, copie ce fichier dans ton site marknotes et lance install.php depuis une URL; cela va installer la dernière version (depuis la production) et le problème de régression sera résolu.

Bonne journée.

**Comment by augras** [comment]
Je viens de faire le nécessaire et je constate qu'une maj a eu lieu puisque la note Introduction est réapparue (toujours version 2.02 par contre) mais toujours pas possible de me connecter.

**Comment by augras** [comment]
ça fonctionne !

**Comment by augras** [comment]
Bon, et bien résolu : merci encore.
Bonne journée,
philippe
