### ISSUE TITLE
Access denied, unauthorized access (carte et ordre chrono) + bouton vider cache disparu

### ISSUE THREAD

**Issue by augras** [cavo789/marknotes#37]
reBonjour Christophe,
Je n'ai jamais essayé ces fonctions avant mais j'ai le message en sujet quand je clique sur Afficher la carte du site et sur Afficher la liste des notes par ordre chronologique inversé.
Par ailleurs le bouton "Vider le cache" défini pour être affiché n'apparaît plus alors qu'il était bien là auparavant.

**Comment by cavo789** [comment]
Merci pour l'info. À force de toujours ajouter des fonctionnalités, il y a des régressions qui apparaissent.

Sitemap et Timeline corrigées.

Pour le bouton Vider le cache, peux-tu aller dans ton écran de paramètres, les options 41.1 Enable the optimization feature et 41.6 Enable cache on the server doivent être actives.

**Comment by augras** [comment]
Pas de soucis. Ca marche beaucoup mieux !
Il me manquait le 41.6.
Bon week-end,
philippe

**Comment by cavo789** [comment]
41.6 autorise la création du cache dans le dossier /cache de ton marknotes ;-)

Je me permets de clôturer cette issue du coup.

Bonne soirée et week-end.
