### ISSUE TITLE
Permissions  fichiers / répertoires -- bonnes pratiques ?

### ISSUE THREAD

**Issue by xantof** [cavo789/marknotes#38]
Bonjour Christophe,

... et mille mercis pour cet outil que j'utilise depuis la V1.
Je fais face à des problèmes d'accès aux fichiers à l'installation : 

Environnements : Ubuntu MATE 18.04 et 17.10, serveur local XAMPP avec PHP 7.2.1
Aussi bien sous Chromium que sous Firefox.

Le script d'installation me donne une page blanche après avoir affiché les choix de versions.  J'ai donc copié le contenu du répertoire /src et lancé /localhost/marknotes/index.php ->

> Warning: include_once(marknotes/includes/debug_show_errors.php): failed to open stream: Permission denied in /opt/lampp/htdocs/marknotes/index.php on line 14

> Warning: include_once(): Failed opening 'marknotes/includes/debug_show_errors.php' for inclusion (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/marknotes/index.php on line 14

> Warning: include_once(marknotes/includes/initialize.php): failed to open stream: Permission denied in /opt/lampp/htdocs/marknotes/index.php on line 16

> Warning: include_once(): Failed opening 'marknotes/includes/initialize.php' for inclusion (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/marknotes/index.php on line 16

> Fatal error: Uncaught Error: Class 'MarkNotes\Includes\Initialize' not found in /opt/lampp/htdocs/marknotes/index.php:17 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/marknotes/index.php on line 17
Ma structure de répertoire :
![marknotesfolder2018-06-24 23-10-09](https://user-images.githubusercontent.com/5675393/41823658-0ca2117a-7804-11e8-9f28-716fb67cd616.png)

J'ai essayé de modifier les niveaux d'autorisation mais je suis de ceux qui on beaucoup de mal avec la logique des droits et niveaux d'accès aux répertoires et fichiers.  Je rencontre ce problème assez systématiquement à chaque nouvelle installation et ca m'embête de tout passer en accès maximal.

Pourrais-tu indiquer les bonnes pratiques à ce sujet?  Quel utilisateur? Quel groupe? Quels niveaux d'autorisation?  [quand j'arrivais à faire fonctionner le script, l'installation attribuait DAEMON à l'utilisateur comme au groupe mais quand je copie le fichier /src, je suis obligé de le faire en tant que superuser et il attribue ROOT:ROOT].
Help!
Stephan

**Comment by cavo789** [comment]
Bonjour Stephan

Un utilisateur depuis la version 1 ? Wow ! Tu es un early adopter ! (merci). J'espère que l'évolution de marknotes va dans le bon sens.

Pour te répondre; désolé mais je suis un utilisateur de Windows (Wamp ou EasyPhp) et pas de Ubuntu dont je connais seulement le nom et rien d'autre (mais j'ai quelques notions Unix évidemment).

Tu me mentionnes le fichier index.php, ligne 14 et donc cette ligne précise : https://github.com/cavo789/marknotes/blob/master/src/index.php#L14

`include_once` est une instruction du langage PHP et je n'ai donc rien à "patcher" ici. C'est donc, oui, bel et bien un souci au niveau du filesystem.

Ta capture d'écran est, me semble-t-il, très parlante : les dossiers sont en `drwx------` c'est-à-dire : `d` pour  dossier pour read-write-execute (7--) pour le propriétaire du fichier et rien du tout pour les autres utilisateurs qui font partie du même groupe et rien du tout pour "tous les autres utilisateurs".

Il s'agit d'un souci de configuration car il faut, au mimum, un droit 7 pour le propriétaire (c'est ok sur ton image) et de 5 (read-execute) pour le groupe et les autres utilisateurs.´

Il te faudrait donc voir la configuration des chmods (je n'y connais rien) afin que ce qui soit installé depuis l'utilisateur web sur ta machine le soit avec un chmod 755.

Désolé, je ne peux pas t'aider plus.

Bonne soirée.

**Comment by cavo789** [comment]
(se connait-on?)

Super pour la place centrale; n'hésite pas si tu as des propositions d'amélioration.

Perso, marknotes est largement devenu central car je l'utilise pour, même, rédiger des mails dont je veux garder une trace (et parce que la rédaction en markdown est tellement plus rapide avec un visuel HTML de qualité (suffit ensuite de copier/coller dans mon mail)) et pour rédiger mes documentations logicielles, même au bureau grâce au plugin INCLUDE qui me permet d'écrire un document qui en inclus d'autres qui peuvent en inclure d'autres ... Je rédige donc les chapitres de ma documentation à part; les sous-chapitres à part; les annexes à part, etc. et même le code source qui est ajouté est inclus avec le plugin INCLUDE.

Je n'ai qu'à afficher le document principal pour que marknotes me génère une doc à jour ;-)

Bonne soirée.

**Comment by augras** [comment]
Bonjour,
Je ne peux que confirmer les propos de Christophe sur les droits.
Mon hébergement mutualisé est sous linux et pour toutes mes appli les dossiers sont en 755 et les fichiers en 644 et tout fonctionne correctement ainsi, y compris marknotes.
Pour certaines application il peut être nécessaire de donner des droits spécifiques à certains dossiers/fichiers pour le groupe www mais dans ce cas s'est généralement indiqué.
Philippe
