### ISSUE TITLE
Barre de menu editeur limitée (sans bouton sauvegarder)

### ISSUE THREAD

**Issue by xantof** [cavo789/marknotes#39]
Bonjour Christophe,

Dans mes tests pour comprendre le fonctionnement des droits sur les fichiers et répertoires, j'ai effectué une installation à partir de zéro.  J'ai téléchargé le zip d'aujourd'hui et utilisé de script d'installation.
Il semble que ca fonctionne sauf qu'il manque des boutons -dont celui de sauvegarde - dans la barre de menu de l'éditeur.  Activer le bouton de nettoyage de cache ne le fait pas apparaître non-plus.
Je n'ai pas approfondi la question, je ne fait que livrer mes découvertes.
![marknotes_2018-06-27 21-30-20](https://user-images.githubusercontent.com/5675393/41995946-9c31152e-7a53-11e8-858b-3f6c1786faa9.png)
Stephan
(je ne pense pas qu'on se connaisse.  J'ai suivi la communauté Joomla pendant un temps mais moi je ne suis qu'un utilisateur, je ne développe pas)

**Comment by xantof** [comment]
Bonsoir Christophe,
OK pour le bouton sauvegarde avec le dernier zip @ 23h30.
Mais je n'arrive toujours pas à afficher la gomme du cache.  Il semble qu'activer le bouton n'a aucun effet.
Stephan

**Comment by xantof** [comment]
Bonsoir Christophe,
OK pour le menu edition, le bouton sauvegarde est de nouveau là avec le dernier zip ~ 23h30.  Merci.
Par contre je n'arrive toujours pas à afficher la gomme du cache.  Il semble que le bouton va-et-vient n'a pas d'effet.
Stephan

**Comment by xantof** [comment]
Bonsoir Christophe,
OK pour le menu de l'éditeur, on peut de nouveau sauvegarder - zip de 23h30.  Merci!
Par contre, je n'arrive toujours pas à faire apparaître la gomme pour vider le cache.
Stephan

**Comment by cavo789** [comment]
Bonjour

Oui pour les boutons de l'éditeur, souci constaté hier après mon upload de 16h00 corrigé vers 20h00 (souci de chemin des fichiers sous Unix (pas Windows)).

Pour le bouton cache celui-ci est aussi conditionné à l'activation des fonctions d'optimisation. As-tu activé l'optimisation de mise en cache ?

Bonne journée
