### ISSUE TITLE
model html : html.js c'est quoi marknotes.message.on_this_page

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#4]
Hello, on définit où cette variable stp ?marknotes.message.on_this_page

**Comment by cavo789** [comment]
Fichier task/showinterface.php mais note que tu perdras ton modification quand tu mettras à jour. 

Sinon essaie juste de la créer dans custom . js qui se trouve à la racine de ton site.

**Comment by cavo789** [comment]
Que souhaites-tu faire au juste ? Changer le texte ? Car si c'est cela direction fichier settings.json où tu peux adapter les textes à tes préférences... 😉

**Comment by elecoest** [comment]
le custom.css n'a pas fonctionné pour moi mais vu que je surcharge le
template html pas de souci :)

http://marknotes.allevents3.com/docs/AllEvents/Modules/module%20calendar.html

manu qui commence a trouvé pas mal le biniou

2017-04-14 18:46 GMT+02:00 Christophe Avonture <notifications@github.com>:

**Comment by elecoest** [comment]
ben çà devrait l'afficher donc sauf que là j'ai une erreur que c'est pas défini comme variable javascript
.

**Comment by cavo789** [comment]
Ok, vu.  Je suis passé sur le PC et j'ai compris ce que tu mentionnais plus haut. Cette erreur a été corrigé mercredi soir, déjà à jour sur le dépôt.

J'avais écris `marknote` et cela aurait dû être `marknotes`.
