### ISSUE TITLE
Intsallation erreur 404 sur /notes/listfiles.json

### ISSUE THREAD

**Issue by monpopoki** [cavo789/marknotes#40]
Bonjour et BRAVO !!!!

Superbe outils.

Je viens de le tester en local, il marche nickel. Lors de l'installation sur le serveur, soit avec l'installer soit avec le zip soit avec la copie de la version locale, le message suivant apparait:

![image](https://user-images.githubusercontent.com/40663874/42033752-33904c8e-7ade-11e8-97ce-694e81ecf28d.png)

Merci

François

**Comment by monpopoki** [comment]
Précisions, en local, je suis sous Windows 10 et le serveur est sous Debian 9

**Comment by cavo789** [comment]
Bonjour François et merci.

Fonctionnel sur localhost mais pas sur ton site => je présume que c'est dans le fichier .htaccess que tu débloqueras la situation.

Vers la ligne 18, tu as trouver la ligne RewriteBase / avec un dièse devant.

Supprime le caractère et sauve le fichier, est-ce mieux ?

**Comment by monpopoki** [comment]
Merci pour la réactivité !
Je viens de faire la manipulation, rien ne change.
Par contre, le mode rewrite n'est pas installé sur mon serveur :-) cela doit venir de la sans doute.

Je fais changer la conf et je reviens pour donner des news.

**Comment by cavo789** [comment]
Ah oui absolument il faut que le mode rewrite soit actif.

**Comment by cavo789** [comment]
Pour info, je vais ajouter un contrôle à l'ouverture de marknotes pour vérifier si mod_rewrite est actif et si ce n'est pas le cas, j'afficherais un message d'information.

Ainsi, ce type de problème arrivera encore (car je souhaite que les URLs soient propres) mais au moins, la cause sera explicite.

**Comment by monpopoki** [comment]
Nous venons d'activer le mode rewrite d'apache. En intervenant sur la ligne 18 commenter ou non, le problème perdure.

Actuellement, nous avons PHP Version 7.0.27-0+deb9u1 sur le serveur et PHP Version 7.0.3 en local. Existe t-il des pré-requis obligatoires (hormis php 7.1 pour nom de fichier accentué ?

Merci

**Comment by cavo789** [comment]
Bonjour

Comme promis, j'ai programmé un contrôle à l'ouverture de l'interface (et j'ai profité de l'occasion pour franciser le texte) : 

![2018-06-29_09h34_56](https://user-images.githubusercontent.com/355999/42079369-d5f869a6-7b7f-11e8-90aa-3ef01fdc8fe2.png)

Si le problème perdure, peut-être dois-tu aussi activer les lignes 17 et 18 ([voir ici](https://github.com/cavo789/marknotes/blob/master/src/htaccess.txt#L17-L18)).  Il s'agit d'un problème d'activation du mode de réécriture, ce n'est pas réellement lié à marknotes. En tout cas, je suis très intéressé par ton feedback afin d'améliorer mon message affiché sur ma capture d'écran ci-dessus.

Pour la version de PHP, marknotes fonctionne avec PHP 7.0 mais comme tu l'as parfaitement compris, la gestion des noms de fichiers avec accents est impossible sous 7.0.x à cause d'un bug dans cette version.

**Comment by monpopoki** [comment]
Je viens de faire une nouvelle installation, toujours à partir de l'installer. Toujours l'erreur avec le message qui apparait bien (en anglais) avec les lignes RewriteBase et Options +FollowSymlinks activées ou pas 
Pour info, le fichier .htaccess généra est différent du fichier htaccess.txt

Précision, l'install est dans un sous-dossier en local comme sur le serveur (/var/www/html/notes).

**Comment by cavo789** [comment]
Tu as essayé RewriteBase /notes càd le nom du sous-dossier ?

Si tu souhaites que je jette un oeil, je peux le faire; il me faudrait alors un accès FTP et l'URL du site. Si cela t'agrée, tu peux m'envoyer les accès avec mon interface sécurisée https://send.aesecure.com (sur mon serveur et tout y est crypté)

**Comment by monpopoki** [comment]
Oui, j'ai déjà essayé, sans succès.

Pour l'accès ce ne sera possible, le serveur est dans notre réseau interne d'entreprise. Je vais passer en revue les écarts entre le phpinfo  local et du serveur ainsi que le paramétrage de Apache.

**Comment by monpopoki** [comment]
On va pouvoir clore ce sujet !!!
La config apache n'était pas bonne ! Je viens de modifier le AllowOverride pour le repertoire /var/www de None à ALL.

**Explication**:
Ce qui m'a mis sur la piste, c'est la différence de .htaccess et du fichier htaccess.txt. Du coup, j'ai purgé le fichier .htaccess et toujours pas de modification.
Après recherche sur la [doc ](https://httpd.apache.org/docs/2.2/fr/mod/core.html#allowoverride) j'ai compris d'ou venait l'erreur:
![image](https://user-images.githubusercontent.com/40663874/42083409-1ffc9134-7b8b-11e8-8d25-4d0e65b9de40.png)

**Comment by cavo789** [comment]
Ah ben oui ! C'est du sabotage ça non ?  ;-)

Merci pour le retour; je clôture.

Bon amusement avec marknotes.
