### ISSUE TITLE
Definition

### ISSUE THREAD

**Issue by monpopoki** [cavo789/marknotes#41]
Bonjour,

J'essaye de comprendre comment fonctionne le plugins _definition_ et je t'avoue que je pige rien du tout ...

Ou faut-il stocker les définitions:
* Dans la notes ?
* Dans un fichier json ?
* Dans un fichier MD ?

Est-ce que les définitions sont globales pour toute l'application ?

Merci pour tes éclaircissements.

François

**Comment by cavo789** [comment]
Salut

Les définitions sont codées (à coder) dans le fichier settings.json. Je n'ai pas encore d'interface pour ce type précis de valeurs (ce n'est pas on/off ni une simple valeur mais des listes de valeurs).

Regarde settings.json.dist et cherche le mot definition (ou glossaey je ne sais plus et je suis sur smartphone en cet instant). C'est expliqué en principe dans ma note sur marknotes.fr.

Le fichier settings.json peut être placé à la racine du site (et donc global pour tout le site) ou dans un dossier ou sous dossier. Exactement comme un fichier .htacces.

Si le fichier n'est pas nommé settings.json mais manote.json alors il s'applique au fichier manote.md (c'est expliqué dans le fichier readme de marknotes). Settings.json est surchargeable.

N'hésite pas à revenir si ce n'est pas clair.

**Comment by cavo789** [comment]
Documentation pour le plugin definitions : https://www.marknotes.fr/docs/marknotes/Plugins/markdown/definitions.html

**Comment by monpopoki** [comment]
Bonjour Christophe,

Je comprend mieux le fonctionnement et du coup, l'importance du fichier settings.json.
Je viens d'insérer dans le fichier settings.json une définition (terms).
Dans ma note le mot **B4** est bien détecté (mise ne forme) par contre, la définition n'apparait pas:

![image](https://user-images.githubusercontent.com/40663874/42312974-e33d44a8-8041-11e8-93d8-e6b75dbae84d.png)

Aurais-je oublié quelque chose ?

Voici le "mardown" de ma note: `Ce texte contient B4 et d'autres mots.`

**Comment by cavo789** [comment]
Je pense qu'il y a la moitié du job qui a été fait... Peux-tu vérifier le fichier settings.json.dist qui se trouve à la racine du site; l'éditer et voir la ligne 640 (https://github.com/cavo789/marknotes/blob/master/src/settings.json.dist#L640). Merci de passer la valeur sur 1, sauver et tester.

En fait, ce plugin-là est en deux parties ; la partie markdown qui va injecter la table des définitions et le plugin html qui va mettre en page (css, ...) les mots et la table. On voit que le mot a été mis en gras/italique (le plugin HTML est donc actif) mais je pense donc que le plugin markdown ne l'est pas.

Il me faut donc trouver une solution aisée pour basculer l'état "enabled" pour les deux plugins; afin de rendre cela aisé.

**Comment by monpopoki** [comment]
Je viens de faire la modification est cela fonctionne Nickel:

![image](https://user-images.githubusercontent.com/40663874/42321656-0ab58492-805a-11e8-9ae5-74de30ce18dc.png)

Merci !

**Comment by cavo789** [comment]
Top

A moi de trouver une astuce alors... Il y a deux notions de "enabled" comme je le mentionnais vu qu'il y a deux plugins; l'un agissant sur le contenu markdown (et donc pourrait être injecté dans une présentation reveal.js p.ex.) et l'autre, qui vient enrichir le HTML produit.

(reste à styliser le glossaire avec un plus joli css ;-) )

**Comment by monpopoki** [comment]
Bonjour Christophe,

Toujours sur mes définitions, j'ai 2 questions (bug ?):
1- Est ce que c'est normal qu'il identifie le terme _erp_ dans le mot perpendiculaire ?
![image](https://user-images.githubusercontent.com/40663874/42454122-f55174d4-838e-11e8-82b9-c01d5f4a5e35.png)


2- Lorsque j'active la modification de la fiche, il insère le glossaire:
![image](https://user-images.githubusercontent.com/40663874/42454092-e85c5c26-838e-11e8-8652-a758f4377aa6.png)

Ce qui, pour effet, si on ne fait pas attention, de créer une note avec le glossaire intégré.

**Comment by cavo789** [comment]
Bonsoir

Non pas bug pour le premier (erp) car c'est une recherche d'occurrences et non de mots. Cela pourrait être amélioré (plugin de type markdown nommé definition).

Pour le second oui vu et corrigé très récemment. Peux-tu vérifier en mettant à jour... (j'ai corrigé le fichier settings.json.dist pour empêcher le plugin de fonctionner dans l'éditeur).
