### ISSUE TITLE
Balise H1 erreur ? 

### ISSUE THREAD

**Issue by Valentin-che** [cavo789/marknotes#42]
Bonjour, 

si je met une balise h1 (#) dans une note, je la vois en mode édition mais plus en mode lecture standard.
![image](https://user-images.githubusercontent.com/25468466/42316223-895d496c-8049-11e8-83ed-318c121ed338.png)
![image](https://user-images.githubusercontent.com/25468466/42316286-ac706d62-8049-11e8-8293-e0586232f637.png)

bonne fin de journée

**Comment by Valentin-che** [comment]
après changement de template et mul rafraichissement :)

![image](https://user-images.githubusercontent.com/25468466/42318421-425ef618-804f-11e8-92fa-42981a9c7c96.png)
![image](https://user-images.githubusercontent.com/25468466/42318461-68dc333c-804f-11e8-974e-f2fe75596fc5.png)

**Comment by cavo789** [comment]
Ton écran est bizarre : une zone de recherche vraiment trop grand et les boutons sur une autre ligne.

Pourrais-tu me donner en privé l'URL de ton site; je regarderai demain.

**Comment by Valentin-che** [comment]
Merci beaucoup ;)
