### ISSUE TITLE
Add RSS support

### ISSUE THREAD

**Issue by Valentin-che** [cavo789/marknotes#43]
Bonjour c'est une simple idée :) 

on peut importer une page html à partir d'une URL
Pourrait on imaginer importer du flux rss et mettre à jour les page importer lorsque celle ci sont mise à jour ( je pense aux page article de blog).
Je suis surement dans un monde de bisounourse :) 

Bon ça fait deux idées :( 
est il possible d'intégrer des notes type code coloré comme un notepad ou un bracket ? 
https://www.dropbox.com/s/2v47shjybvqztyu/Capture%20d%27%C3%A9cran%202018-07-06%2023.58.40.png?dl=0

:D

**Comment by cavo789** [comment]
Bonjour Valentin

1. RSS

Désolé mais cela sort du cadre de marknotes qui est un gestionnaire de notes (en tout cas de mon objectif). Si quelqu'un souhaite intégrer cela, cela pourrait être fait sous la forme d'un plugin de type tasks avec, derrière, un job à mettre dans un crontab. Attention aussi avec la gestion de la source : si tu édites une note ayant été créées depuis un RSS et si l'auteur du fil RSS modifie la note; quelle version garder ? Celle que tu as modifiée ou la nouvelle ? Pas simple. Je mets le label "help wanted" pour cette partie RSS car je ne compte pas, personnellement, travailler dessus.

2. Coloration

Depuis l'éditeur, cela ne fonctionnera pas car le langage markdown ne gère pas la mise en couleur toutefois c'est déjà intégré en mode html.

Ci-dessous une partie du code de markdown.js. Vois comment je l'ai écris et copie/colle-le dans une de tes notes et affiche le rendu html (ou reveal p.ex.), tu auras la coloration grâce à [Prism](https://github.com/PrismLibrary/Prism) intégré dans marknotes.

```javascript

if (marknotes.autoload === 1) {

	// Be sure that this plugin is well part of the current
	// Prism installation and is loaded
	if (typeof Prism === 'object') {
		if (Prism.plugins.NormalizeWhitespace) {
			Prism.plugins.NormalizeWhitespace.setDefaults({
				'break-lines': 120 // Soft wrap after 120 chars
			});
		}
	}

	// On page entry, get the list of .md files on the server
	if (marknotes.hasOwnProperty('message')) {
		Noty({
			message: $.i18n('loading_tree'),
			type: 'info'
		});
	}
}
```
