### ISSUE TITLE
Dossier - Nom

### ISSUE THREAD

**Issue by ghost** [cavo789/marknotes#44]
Iaorana Christophe,

J'ai créé un dossier " Tool's " puis ajouté une note et enfin téléversé une image .
Lors de l'affichage, la note est correcte mais les images ne s'affichent pas.

**Le problème vient du caractère '** (apostrophe) dans nom de dossier. je l'ai supprimé et tout fonctionne.

Est-ce une restriction logique ? si oui y en a t-il d'autres ?
Est-ce un bug ?

Merci

François

**Comment by cavo789** [comment]
Bonjour

Une apostrophe est un caractère en principe interdit dans une URL car un tel caractère est utilisé pour mener des attaques de type injection SQL (sur des sites avec bases de données derrière).

Vu que le nom du dossier est partie intégrante de l'URL et qu'une URL encodée (avec des %20 par exemple pour coder un espace) est très moche, oui, je n'ai pas fait d'effort pour gérer les apostrophes puisque nativement, comme expliqué plus haut, le blocage est la bonne technique.

Si marknotes a permis la création du dossier depuis son interface alors je devrais l'interdire. Si tu a créé le dossier manuellement, directement sur ton filesystem, oui il ne sera pas géré.

**Comment by monpopoki** [comment]
Iorana !

Ok, merci pour l'explication.
J'ai pu le créer à partir du gestionnaire de fichier de Marnotes.

**Comment by cavo789** [comment]
TODO @Christophe pour voir s'il est possible de restreindre la création d'un dossier dans EL Finder (le gestionnaire de fichiers) afin de ne pas autoriser certains caractères comme l'apostrophe.
