### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#46]
Hello j'ai activé le chargement des custom file
mis un custom.css a la racine de marknotes
Mais il n'est pas chargé ... une idée ?

**Comment by cavo789** [comment]
Bonjour

Pourquoi ne pas personnaliser ton template ? 

Prends le fichier settings.json et ajoute ce bloc : 

```json
	"templates": {
		"interface": "micker"
	}
```

Va dans le dossier /templates et duplique le fichier `interface.php` et nomme-le `micker.php`.

Voilà, maintenant ton site marknotes affiche ton template (pour l'interface).

Édite `micker.php` et amuse-toi ;-)

**Comment by micker** [comment]
.. oui mais comme il y avait l'option ...
