### ISSUE TITLE
Changer le lien sur le logo

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#47]
c'est possible de changer le lien sur le logo en haut à gauche ?

**Comment by cavo789** [comment]
Bonjour

Pourquoi ne pas personnaliser ton template ? 

Prends le fichier settings.json et ajoute ce bloc : 

```json
	"templates": {
		"interface": "micker"
	}
```

Va dans le dossier /templates et duplique le fichier `interface.php` et nomme-le `micker.php`.

Voilà, maintenant ton site marknotes affiche ton template (pour l'interface).

Édite `micker.php` et amuse-toi ;-)

**Comment by micker** [comment]
oki je vais regardé
