### ISSUE TITLE
Enlever des &nbsp;

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#48]
hello je suis en train de finir la documentation de Flexicontent avec marknotes
c'est extrait avec le composant md2manifest
dans les md générés j'ai des &nbsp; qui s'affichent ... https://flexicontent.org/_documentation_notes/docs/fr-FR/flexicontent/modules/FLEXIcontent%20-%20Module%20de%20Filtrage.html
tu verais comment faire pour les viré automatiquement ?
Merci

**Comment by cavo789** [comment]
Bonjour Yannick

Tu peux me poster une capture d'écran s'il te plaît parce que ton message ci-dessus ne me permets pas de comprendre.

Note : si ce que tu veux supprimer est dans la note .md, ce n'est pas trop la tâche de marknotes de nettoyer le fichier ;-)

**Comment by micker** [comment]
en fait j'ai trouver c'est dans le composant qui créer les MD ..
Merci d'avoir permis de rendre la doc de flexicontent possible !

**Comment by cavo789** [comment]
Super !

Bonne journée
