### ISSUE TITLE
table html en screen.php <>  html.php

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#5]
Hello Christophe,

Comme faire pour avoir le même rendu pour les tables html dans le template html ? J'ai retiré datatables mais je souhaite quand même que les tables soient sexy :)

Merci

**Comment by cavo789** [comment]
Correct ! Je n'ai pas fait attention.

Avec l'inspecteur des éléments, ajoute la div ci-dessous avant ton tableau et ajoute les classes mentionnées ci-dessous comme attribut du tableau.

```html
<div class="table-responsive">
   <table class="table table-striped table-bordered table-hover">
   </table>
</div>
```

Si tu penses que c'est nettement mieux, j'ajouterai cela dans la prochaine version.

**Comment by elecoest** [comment]
euh, sauf que c'est pas moi qui génère la table c'est l'outil. Je mets çà
dans un template ?

Le 17 avril 2017 à 09:05, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by cavo789** [comment]
Je parlais de l'*inspecteur des éléments*, càd touche F12 sur ton navigateur, inspecter l'élément -> cliquer sur ton tableau et modifier le code HTML.

Mais laisse tomber, je vais inclure ce dev dans la prochaine version.

**Comment by elecoest** [comment]
pas de souci, j'avais pas compris. dsl

Le 17 avril 2017 à 09:57, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by cavo789** [comment]
Done, added in 1.0.8
