### ISSUE TITLE
PDF dans barre de navigation

### ISSUE THREAD

**Issue by bbdbois** [cavo789/marknotes#50]
Iorana !

Est-il possible de faire apparaitre des fichiers PDF dans la barre de navigation ?
Et est-il possible que " plugin " de recherche intègre le contenu des PDF ?

Merci

françois

**Comment by bbdbois** [comment]
Merci pour tes réponses.

En fait, pour l'affichage des fichier PDF, j'aimerai savoir si il est possible de le faire apparaitre sur la sidebar:

![2018-10-10 15_37_43-edito](https://user-images.githubusercontent.com/30286296/46740177-7a189600-cca2-11e8-912d-ad121df62f35.png)

L'objectif étant de mixer des notes markdown et des fichiers PDF.

Pour la recherche, il effectivement mieux de privilégier la rapidité.

Merci

**Comment by cavo789** [comment]
Non, la sidebar (ce que je nomme treeview) ne remonte que les fichiers .MD.

S'il faudrait modifier ce comportement, le point d'entrée est ici : https://github.com/cavo789/marknotes/blob/master/src/marknotes/plugins/task/listfiles/treeview.php

Mais cela va impliquer bien plus que ça car cliquer sur un lien depuis le treeview génère une action ajax pour obtenir le code HTML (une fois .md converti) or ici, point de conversion, ce serait pour afficher le PDF.

Ce que je ferais à ta place : j'utiliserai le plugin INCLUDE pour afficher une et une seule note qui reprendra la liste des fichiers .pdf sur mon serveur.

Voir https://www.marknotes.fr/docs/marknotes/Plugins/markdown/listfiles.html
