### ISSUE TITLE
Problème avec TOC

### ISSUE THREAD

**Issue by sabrina974** [cavo789/marknotes#51]
Bonjour,

J'ai bien mis %TOC_6%, mais il me met un sommaire qu'avec les titres de niveaux 2 (##titre niv 2).
Je galère donc pour me créer un sommaire.
![image](https://user-images.githubusercontent.com/4637575/48947798-b3475580-ef32-11e8-9228-8b32293983da.png)
Alors que 
![image](https://user-images.githubusercontent.com/4637575/48947816-c528f880-ef32-11e8-86c1-fdfae429c185.png)
Merci de votre aide

Sabrina

**Comment by sabrina974** [comment]
Re bonjour,

J'ai d'ailleurs créé une nouvelle note,

Et j'ai le même problème 

![image](https://user-images.githubusercontent.com/4637575/48948082-952e2500-ef33-11e8-8a54-c325c00e3b64.png)
![image](https://user-images.githubusercontent.com/4637575/48948101-9fe8ba00-ef33-11e8-811d-4f8d120c233b.png)

**Comment by sabrina974** [comment]
### **C'est bon j'ai compris où était le problème.**

C'est résolu !!!!

> 
> 
> Bonjour,
> 
> J'ai bien mis %TOC_6%, mais il me met un sommaire qu'avec les titres de niveaux 2 (##titre niv 2).
> Je galère donc pour me créer un sommaire.
> ![image](https://user-images.githubusercontent.com/4637575/48947798-b3475580-ef32-11e8-9228-8b32293983da.png)
> Alors que
> ![image](https://user-images.githubusercontent.com/4637575/48947816-c528f880-ef32-11e8-86c1-fdfae429c185.png)
> Merci de votre aide
> 
> Sabrina

### **C'est bon j'ai compris où était le problème.**

C'est résolu !!!!

**Comment by cavo789** [comment]
J'ai l'impression que tu n'as pas compris (à voir tes captures d'écran) la notion des titres en langage markdown. Je peux me tromper mais sache que le niveau des titres (titre 1, titre 2, titre 3, ...) est défini par le nombre de dièses utilisé.

```markdown
# Titre 1
## Titre 1.1
## Titre 1.2
### Titre 1.2.1
```

Un dièse = titre 1
Deux ... = titre 2; sous-niveau de titre 1
jusqu'à six (max).

Bonne soirée
