### ISSUE TITLE
intro

### ISSUE THREAD

**Issue by sabrina974** [cavo789/marknotes#52]
Bonjour,

Peut on personnaliser l'intro ?

Merci

**Comment by cavo789** [comment]
Bonjour

Que nommes-tu intro ?

**Comment by sabrina974** [comment]
C'est en faite, l'aide qui s'affiche à l'ouverture du site 
![image](https://user-images.githubusercontent.com/4637575/49152144-33decb00-f312-11e8-81c3-ea9d45e4883c.png)

**Comment by cavo789** [comment]
Ce n'est pas prévu pour être adapté; c'est une découverte de l'interface. Tu peux activer / désactiver cette fonctionnalité depuis les paramètres de marknotes mais pas en modifier le comportement.

Par curiosité; que souhaitais-tu faire ?

**Comment by sabrina974** [comment]
En faite, je souhaitais, ajouter d'autres éléments adapté a mon contenu.

**Comment by cavo789** [comment]
L'intro n'est pas "en fonction du contenu" mais en fonction des fonctionnalités de Marknotes.

Si tu vas voir le code source du fichier /template/interface.php, tu pourras voir comment cela fonctionne (chercher `data-intro`) et adapter le code par toi-même au besoin.

Je me permets de fermer cette demande du coup.
