### ISSUE TITLE
Page par défaut

### ISSUE THREAD

**Issue by sabrina974** [cavo789/marknotes#53]
Bonjour,

Peut afficher une page par défaut dés que les personnes arrives sur le site ?

Merci

**Comment by cavo789** [comment]
Va voir les options, partie "31 Homepage"

Il existe une option pour cela et tu peux une note existante (et une seule)

![2018-11-28_12h20_21](https://user-images.githubusercontent.com/355999/49148559-f8d79a00-f307-11e8-8d2c-6bbdcb18e035.png)

Bonne journée.

**Comment by sabrina974** [comment]
Rebonjour,

JE précise que j'ai modifié le treeview, mais ça n'a rien changé. J'ai suivi le tuto 👍 
[Define your preference](https://github.com/cavo789/marknotes/wiki/4.1-Define-yours-preferences)

J'ai donc ajouté le champ 👍 
"treeview": {
                    "default": "docs/ma_note.md",
manote_md étant la note que je veux voir apparaître par défaut et qui se trouve dans le répertoire docs.
J'ai également mis sans le répertoire docs, mais rien.
Merci d'avance

**Comment by cavo789** [comment]
Essaie au moyen des paramètres s'il te plaît; vois ma précédente réponse.
