### ISSUE TITLE
Connexion et LISTFILES 

### ISSUE THREAD

**Issue by nobody-debug** [cavo789/marknotes#55]
Bonjour Christophe,

J'utilise marknotes depuis peu et j'ai remarqué deux choses : 

- Lorsque je souhaite mettre en place une page login sur le site marknotes bloquant tout accès au site sans connexion, la login form ne fonctionne pas avec mon id et mdp de connexion renseigné. Elle reste inactive et la connexion est donc impossible. est-ce connu comme problème ?

- Le second point est l'inefficacité de la commande LISTFILES. malgré sa mise en place dans une note et faisant référence à son dossier (qui comprends différents doc en pièces jointes) aucunes liste ne se créé. Y a t'il un bug connu sur cette fonction ou est-ce moi qui ne l'utilise pas correctement ?

Merci d'avance pour tes réponses,

cdt,
Romain

**Comment by cavo789** [comment]
Bonjour Romain

1. As-tu vérifié ta console de debugging (touche F12 onglet console) pour voir si tu aurais un quelconque message d'erreur (comme un conflit JS)

2. En effet, je pense plutôt à un petit souci sur l'utilisation car j'utilise régulièrement LISTFILES.
Le dossier doit être écrit en relatif par rapport à la localisation de la note. Si ta une note est p.ex. dans le dossier `/docs/fournisseurs/factures.md`, tu pourrais avoir un dossier tel que `/docs/fournisseurs/.factures` et, du coup la bonne syntaxe serait `%LISTFILES .factures%` dans ton fichier  `/docs/fournisseurs/factures.md`.

**Comment by nobody-debug** [comment]
Merci, pour ta réponse. Le problématique du plugin LISTFILES était bien liée à un problème d'utilisation de ma part. Elle fonctionne correctement.

Concernant la problématique de login screen avant d'accéder à l'interface, j'ai regardé la console de debugging comme tu me l'a conseillé. A vrai dire j'ai du mal à dire s'il y un conflit JS. Je te joins une capture d'écran des erreurs détectées.
[Capture_console.pdf](https://github.com/cavo789/marknotes/files/3452846/Capture_console.pdf)

**Comment by cavo789** [comment]
Bonjour

Les lignes en rouges font preuve d'un problème javascript et du coup, l'écran de login est désactivé car reposant partiellement sur du JS.

Il faudrait aller plus loin dans l'analyse de la première ligne en rouge qui fait état d'un souci dans le script index.php en ligne 50. Si tu fais un view-source et que tu te rends sur cette ligne 50, il serait peut-être possible de comprendre en voyant la ligne.

**Comment by nobody-debug** [comment]
Bonjour,

Voici la ligne en erreur (voir pièce jointe).
ça serait lié au debug ?

**Comment by cavo789** [comment]
Salut

Il manque la pièce jointe. Marknotes dispose d'un mode debug; j'ai l'impression que tu dis l'avoir activé; si tu penses qu'il serait la cause du souci, désactive-le. Dans ton fichier /settings.json (à la racine du site) mets "debug" sur 0.

Bonne journée.

**Comment by nobody-debug** [comment]
Bonjour Philippe,

J'étais absent et je n'ai pu te répondre. J'avais bien modifié mes options de debug dans /settings.json mais cela ne change rien. L'erreur est dans le fichier index.php :
```
	<script>
		var marknotes = {};
		marknotes.arrPluginsFct = [];
		marknotes.isBot = 0;
		marknotes.settings = {};
		marknotes.settings.debug =% DEBUG %;
		marknotes.webroot = 'https://personnalnotes.yj.fr/';
	</script>
```
Le message d'erreur est **//Uncaught SyntaxError: Unexpected token %** pour la ligne _marknotes.settings.debug =% DEBUG %;_ 

Merci par avance de ton aide,
Romain

**Comment by cavo789** [comment]
Bonjour Jean-Paul 

_(moi, c'est Christophe ;) )_

La ligne devrait être 

```javascript
marknotes.settings.debug='%DEBUG%';
```

Il ne faudrait pas d'espace entre les signes `%` et le mot DEBUG; ce que tu me montres est du coup étonnant.

Vérifie le fichier `/src/templates/html.php` ainsi que `/src/templates/interface.php`.  Cherche le mot "debug" et vérifie l'absence d'espace. 

Sinon, plus simple, supprime la ligne `marknotes.settings.debug = '%DEBUG%';` que tu trouveras dans les deux fichiers; cela solutionnera ton problème.

Bonne soirée Marc.

**Comment by nobody-debug** [comment]
Bonjour Christophe,

Désolé je devais être vraiment ailleurs quand je t'ai écris hier... :)

Je bloque toujours sur ma problématique et a vrai dire je m'arrache les cheveux. J'ai bien supprimé les lignes comme tu me l'as indiqué, cependant les erreurs se maintiennent malgré que je vide le cache...

Voici l'adresse permettant d'accéder à mon site (https://personnalnotes.yj.fr/) avec la page d'accueil connexion qui bloque. Peut-être que les autres erreurs JS te parleront plus..

Bonne journée
