### ISSUE TITLE
Mermaid et Mindmap ne fonctionne pas

### ISSUE THREAD

**Issue by Jackie16** [cavo789/marknotes#56]
Bonjour et merci pour le magnifique travail accompli avec MarkNotes.
J'ai installé Marknotes sans soucis sur mon serveur perso (Ubuntu / Webmin / Virtualmin).
Je rencontre cependant un soucis concernant Mermaid et Mindmap. J'ai bien implémenté comme indiqué dans les exemples pour Mermaid dans le setup et pour mindmad en modifiant le fichier settings.json mais rien n'y fait. La mise en forme ne se fait pas. Je dois certainement louper quelque chose... Pouvez m'aider s'il vous plait.
Bien Cordialement 
Jackie

**Comment by cavo789** [comment]
Bonjour

Afin que je puisse tester sur ma machine, peux-tu me copier ici le source de ton markdown ?

Bonne journée

**Comment by Jackie16** [comment]
Bonjour Christophe,
Merci pour ton retour mon source est le source officiel (Marknotes v2.1.0) que j'ai pris sur ton Github marknotes. 

Bonne fin de WE
Jackie

**Comment by cavo789** [comment]
rebonjour Jackie

Je viens de regarder et cela semble être lié à l'utilisation du plugin htmlindent qui vise à reformarter le code HTML généré par Marknotes pour que ce code soit propre.

Je te suggère de désactiver le plugin comme ceci : dans la liste des plugins de type task, il faut mettre la propriété enabled pour htmlindent sur zéro.

J'avais le même problème que toi sur mon site et maintenant c'est résolu : https://www.marknotes.fr/docs/marknotes/Plugins/page/html/mermaid.html

Bonne soirée.

```json
{
    "plugins": {
        "task": {
            "htmlindent": {
                "enabled": "0"
            }
        }
    }
}
```

**Comment by Jackie16** [comment]
Bonjour Christophe,
Merci pour ton aide, je viens d'essayer mais cela ne fonctionne qu'a moitié. L'affichage en HTML ne fonctionne pas mais cela fonctionne en mode présentation.
J'ai bien vérifié de mettre le cache du navigateur (Chrome) à zéro et dans le doute j'ai essayé avec Opéra et Firefox et j'ai le même résultat.
Il doit y avoir un autre paramètre qui bloque.
Bonne soirée

**Comment by cavo789** [comment]
J'ai apporté la modification sur mon site de démo (https://www.marknotes.fr/docs/marknotes/Plugins/page/html/mermaid.html) et à moins que quelque chose m'échappe, la fonctionnalité mermaid y est fonctionnelle.

Si ton fichier settings.json n'est pas confidentiel (càd si pas de login/password), peux-tu copier/coller ici son contenu ?

**Comment by Jackie16** [comment]
Voici mon fichier settings.json

{
    "debug": {
        "development": "1",
        "enabled": "1"
    },
    "interface": {
        "skin": "blue-light"
    },
    "plugins": {
        "buttons": {
            "copyhtml": {
                "quickIcons": "1"
            },
            "docx": {
                "quickIcons": "0"
            },
            "epub": {
                "quickIcons": "1"
            },
            "md": {
                "quickIcons": "1"
            },
            "odt": {
                "quickIcons": "1"
            },
            "pdf": {
                "quickIcons": "1"
            },
            "remark": {
                "quickIcons": "1"
            },
            "timeline": {
                "quickIcons": "1"
            },
            "txt": {
                "quickIcons": "1"
            }
        },
        "content": {
            "html": {
                "balloon": {
                    "enabled": "1"
                },
                "bootstrap": {
                    "enabled": "1"
                },
                "tags": {
                    "enabled": "1"
                }
            }
        },
        "options": {
            "content": {
                "html": {
                    "bootstrap": {
                        "tables": {
                            "responsive": "1"
                        }
                    }
                }
            },
            "markdown": {
                "encrypt": {
                    "password": ""
                }
            },
            "page": {
                "html": {
                    "mermaid": {
                        "theme": "dark"
                    }
                }
            },
                "login": {
                    "password": "",
                    "username": ""
                },
                "robots-txt": {
                    "disallow_all": "1"
                }
            }
        },
        "page": {
            "html": {
                "introjs": {
                    "enabled": "0"
                },
                "mindmap": {
                    "enabled": "1"
                },
                "robots": {
                    "enabled": "0"
                },
                "smileys": {
                    "enabled": "1"
                },
                "together": {
                    "enabled": "1"
                }
            }
        },
        "task": {
            "encrypt": {
                "enabled": "1"
            },
            "htmlindent": {
                "enabled": "0"
            },
            "login": {
                "enabled": "1"
            },
            "optimize": {
                "enabled": "1"
            }
        }
    },
    "regional": {
        "language": "fr",
        "locale": "fr-FR",
        "timezone": "Europe\/Paris"
    },
    "site_name": "marknotes - Gestion des notes"
}



J'ai retiré les infos login et password.

Merci encore pour ton aide,

**Comment by cavo789** [comment]
Si c'est exactement le code de ton fichier settings.json, celui-ci n'est pas valide.

Si tu copies/colles ton code ci-dessus dans mon outil https://jsonlint.avonture.be/ tu verras qu'il y a un problème.

Je te propose de remplacer temporairement ton fichier settings.json par ce seul contenu:

```json
{
    "plugins": {
        "task": {
            "htmlindent": {
                "enabled": "0"
            }
        }
    }
}
```

et je pense que tu pourras voir que cela fonctionne (c'est le cas chez moi).

Bonne soirée

**Comment by Jackie16** [comment]
Je viens de faire l'essai en remplacent mon fichier d'origine settings.json par ton exemple et j'ai le même souci. Cela fonctionne mais pas sous HTML uniquement en mode présentation.

j'ai re-nettoyé mon fichier perso settings.json et l'ai testé sur ton site il n'y a plus d'erreur:

Je met le code en bas de ce post au cas ou mais je pense que c'est un problème plus profond. Peut être la configuration de mon serveur. Je ne veux pas te faire perdre trop de temps c'est déjà sympa de m'avoir consacré un moment. je vais chercher de mon coté et si je trouve quelque chose je met à jour ce post.
Merci encore pour ton aide.
Bonne Soirée
Jackie

Fichier perso settings.json
{
    "debug": {
        "development": "1",
        "enabled": "1"
    },
    "interface": {
        "skin": "blue-light"
    },
    "plugins": {
        "buttons": {
            "copyhtml": {
                "quickIcons": "1"
            },
            "docx": {
                "quickIcons": "0"
            },
            "epub": {
                "quickIcons": "1"
            },
            "md": {
                "quickIcons": "1"
            },
            "odt": {
                "quickIcons": "1"
            },
            "pdf": {
                "quickIcons": "1"
            },
            "remark": {
                "quickIcons": "1"
            },
            "timeline": {
                "quickIcons": "1"
            },
            "txt": {
                "quickIcons": "1"
            }
        },
        "content": {
            "html": {
                "balloon": {
                    "enabled": "1"
                },
                "bootstrap": {
                    "enabled": "1"
                },
                "tags": {
                    "enabled": "1"
                }
            }
        },
        "options": {
            "content": {
                "html": {
                    "bootstrap": {
                        "tables": {
                            "responsive": "1"
                        }
                    }
                }
            },
           "page": {
                "html": {
                    "mermaid": {
                        "theme": "dark"
                    }
                }
            },
        },
        "page": {
            "html": {
                "introjs": {
                    "enabled": "0"
                },
                "mindmap": {
                    "enabled": "1"
                },
                "robots": {
                    "enabled": "0"
                },
                "smileys": {
                    "enabled": "1"
                },
                "together": {
                    "enabled": "1"
                }
            }
        },
        "task": {
            "encrypt": {
                "enabled": "1"
            },
            "htmlindent": {
                "enabled": "0"
            },
            "login": {
                "enabled": "1"
            },
            "optimize": {
                "enabled": "1"
            }
        }
    },
    "regional": {
        "language": "fr",
        "locale": "fr-FR",
        "timezone": "Europe\/Paris"
    },
    "site_name": "marknotes - Gestion des notes"
}

**Comment by cavo789** [comment]
Juste pour être sûr: que veux-tu dire par "Cela fonctionne mais pas sous HTML uniquement en mode présentation.".

Sous HTML, c'est dans une nouvelle page ? Comme dans mon exemple https://www.marknotes.fr/docs/marknotes/Plugins/page/html/mermaid.html ? (parce que, sauf si quelque chose m'échappe; sur mon site, c'est fonctionnel). Pour info, mon source est accessible en remplaçant .html par .md et donc https://www.marknotes.fr/docs/marknotes/Plugins/page/html/mermaid.md.

**Comment by Jackie16** [comment]
J'ai recopié mermaid.md dans mon dossier docs et voici un extrait de copie d'écran:
![image](https://user-images.githubusercontent.com/57058840/67641890-6a4c0e00-f906-11e9-994a-0665effdceca.png)

**Comment by cavo789** [comment]
Ok, ouvre s'il te plaît cette note dans une  nouvelle fenêtre. Tu as une icône pour cela en haut à droite.

Tu verras, en principe, cela va "solutionner" le problème.

Pourquoi ? Parce que le rendu d'un mermaid requiert l'inclusion d'un code javascript et d'un "render" qui est exécuté en mode .html (nouvelle fenêtre) et pas dans l'interface.

**Comment by Jackie16** [comment]
Yes !!! Effectivement cela fonctionne à merveille. Il suffisait de le savoir :)

Merci beaucoup pour ton dévouement et le temps passé c'est tout bête mais j'aurais pu chercher un moment, je pense même que je n'aurais jamais trouvé moi-même.

Marknotes est un super logiciel qui mérite que l'on s'y attarde je l'utilise depuis 3 semaine et je migre toutes mes notes de onenotes vers mon serveur perso. L'énorme avantage de Marknotes est qu'il est Open source et que je pourrai le faire évoluer au fur et à mesure de mes besoins. C'est un gage de longévité.

Bonne soirée Christophe et merci encore pour ton travail.

**Comment by cavo789** [comment]
>Yes !!! Effectivement cela fonctionne à merveille. Il suffisait de le savoir :)
Pourtant j'ai dû le mentionner quelque part ;-)

Cela étant, il y avait quand même le souci avec le plugin htmlindent que je propose de désactiver; ce que tu as donc fait.

Bonne soirée Jackie.
