### ISSUE TITLE
contact form : not hide after connect

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#7]
Hello,

after connexion, i've a information "Connected ok" but the contact form is still on the top. You can close it so it's not a blocking bug

**Comment by cavo789** [comment]
Yep, already see it, thanks...  Should indeed improve this form. Also, by pressing enter on the password field, it should start the login process (today we're forced to clic on the button).

**Comment by cavo789** [comment]
Solved in 1.0.8
