### ISSUE TITLE
comment trier le treeview par ordre alphabétique ?

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#8]
dans la vue saisie, l'idée consiste à trier mes notes par nom de fichier.

Je pense que çà doit être un paramètre à passer à la fonction treeview, mais où ? merci

**Comment by cavo789** [comment]
Je viens de regarder; pas évident car il ne semble pas faire correctement la distinction minuscules/majuscules malgré que je lui donne "l'ordre" de le faire. Dans la 1.0.8, il y aura toutefois une amélioration du tri mais pas idéale toutefois car triant les fichiers et les dossiers; je continuerai à regarder ça.

**Comment by cavo789** [comment]
Corrigé; j'ai opéré au tri dans la fonction $aeFiles->rglob() càd en PHP (fichier marknotes/files.php)

![2017-04-19_10h25_09](https://cloud.githubusercontent.com/assets/355999/25170363/99a16274-24ea-11e7-9a9d-5b6fe2e42674.png)

Sera disponible dans le prochain commit.

**Comment by elecoest** [comment]
parfait c'est vraiment cool !

2017-04-19 10:26 GMT+02:00 Christophe Avonture <notifications@github.com>:
