### ISSUE TITLE
comment ouvrir le treeview sur une note particulière

### ISSUE THREAD

**Issue by elecoest** [cavo789/marknotes#9]
hello,

j'ai une petite question  :  j'ai une note qui reprend des liens vers d'autres notes. Comment ouvrir cette note dans le treeview en mode URL ?

**Comment by cavo789** [comment]
Depuis l'interface cela n'existe pas. Cela reste à développer mais astuce tu peux, tu l'as déjà mis en musique, précomplété le champs de recherche avec des tags. Cela peut t'aider.

**Comment by elecoest** [comment]
OK. je vais regarder un peu çà


2017-04-17 21:38 GMT+02:00 Christophe Avonture <notifications@github.com>:

**Comment by cavo789** [comment]
Laisse, je vais regarder de mon côté, j'irais certainement plus vite pour cela.

**Comment by elecoest** [comment]
je pensais m'en sortir avec les paramètres pour le router mais non c'est
plus compliqué que çà :)


Le 18 avril 2017 à 10:59, Christophe Avonture <notifications@github.com> a
écrit :

**Comment by cavo789** [comment]
La programmation a été faite mais génère une complexité au niveau du treeview qui doit recevoir un nouveau paramètre de manière dynamique (charger ou pas le plugin state de jstree). Affaire à suivre...

**Comment by cavo789** [comment]
Voilà, c'est codé. Voir https://github.com/cavo789/marknotes/wiki/4.1-Define-yours-preferences -> treeview -> default.

Sera disponible lors du prochain commit ;-)
